updated Ian talk
RSE-Sheffield/RSE-Sheffield.github.io pull request #131
Opened 2019-09-03 09:26 UTC by mozhgan-kch

2019-09-03 10:32 UTC, ptheywood requested changes
Would it be possible to upload a PDF rather than the pptx file instead? Generally PDFs are more portable than pptx files.

2019-09-03 10:34 UTC, Robadob commented
![both](https://66.media.tumblr.com/612ac846ba9b0857666cae0443f5f48e/tumblr_n2x5iyjNh41qece2io3_400.gif)

2019-09-23 20:57 UTC, mozhgan-kch commented
pdf added.

2019-09-24 09:01 UTC, willfurnass approved these changes

2019-09-24 09:01 UTC, merged