Issue143
RSE-Sheffield/RSE-Sheffield.github.io pull request #145
Opened 2019-09-30 10:04 UTC by bobturneruk

Resolves issue #143, for the time being, by removing the intermittently broken calendar widget and related link. Slot times are visible on the booking form.

2019-09-30 10:34 UTC, willfurnass requested changes

2019-09-30 10:34 UTC, willfurnass commented on pages/support/code-clinic.md
> -Note that **slots can only be booked 48 hours or more before the scheduled time**.
We want to keep that second deleted sentence.  

Rework the first deleted sentence so it mentions that you can choose an appointment from a list of free slots via the booking form?

2019-09-30 10:41 UTC, willfurnass approved these changes

2019-09-30 10:48 UTC, bobturneruk commented on pages/support/code-clinic.md
> -Note that **slots can only be booked 48 hours or more before the scheduled time**.
I think that the restructured version I've just committed is a little better.

2019-10-02 14:03 UTC, ptheywood requested changes

2019-10-02 14:03 UTC, ptheywood commented on pages/support/code-clinic.md
> +
The 48hr cutoff statement has been removed again by the latest commit. 

> Note that **slots can only be booked 48 hours or more before the scheduled time**.

2019-10-02 14:47 UTC, bobturneruk commented on pages/support/code-clinic.md
> +
I think this is under the "Book a slot" heading on the Issue143 branch. Is this OK?

2019-10-02 16:16 UTC, willfurnass commented on pages/support/code-clinic.md
> +
ok

2019-10-02 16:17 UTC, ptheywood commented on pages/support/code-clinic.md
> +
Yep that's fine, just not visible on the diff.

2019-10-02 16:18 UTC, ptheywood approved these changes

2019-10-02 16:20 UTC, merged