Ak events
RSE-Sheffield/RSE-Sheffield.github.io pull request #243
Opened 2020-04-21 12:56 UTC by annakrystalli

Add ReproHack and RSS events

2020-04-21 14:13 UTC, willfurnass requested changes
Looks good.  I've suggested two small formatting changes.

Would be good to add other Reprohacks to list of past events at some point but can leave for another PR.

2020-04-21 14:13 UTC, willfurnass commented on _events/workshop-2020-05-14-remote-reprohack.md
> +- Leiden NL ReproHack: https://www.software.ac.uk/blog/2020-01-15-reproducibility-hackathon-netherlands-aftermath
```suggestion
Read more about previous ReproHacks on the [Software Sustainability Institute](https://www.software.ac.uk)'s blog:

- [Manchester Carpentry Connect ReproHack](https://www.software.ac.uk/blog/2019-08-07-reprohacking-carpentryconnect-manchester-2019)
- [Leiden NL ReproHack](https://www.software.ac.uk/blog/2020-01-15-reproducibility-hackathon-netherlands-aftermath)
```

2020-04-21 14:13 UTC, willfurnass commented on _events/workshop-2020-05-14-remote-reprohack.md
> +In the run-up to the event, you can submit details of your paper, code and data for reproduction and review here: https://sheffield-university.shinyapps.io/n8cir-reprohacks/
```suggestion
In the run-up to the event, you can [submit details of your paper, code and data for reproduction and review here](https://sheffield-university.shinyapps.io/n8cir-reprohacks/).
```

2020-04-21 14:16 UTC, willfurnass commented
NB the embedded EventBrite frame isn't showing for me on the ReproHack event page in either Firefox or Chromium (I get an `X-Frame-Options` warning placeholder in Firefox).  Don't think that should block the merging of this PR - will open a separate Issue for this.

2020-04-21 15:05 UTC, willfurnass requested changes

2020-04-21 15:05 UTC, willfurnass commented on _events/workshop-2020-05-14-remote-reprohack.md
> +eventbrite_id: https://www.eventbrite.co.uk/e/remote-reprohack-tickets-102069657092
Recommend deleting this `eventbrite_id` line as causes errors to be rendered; see Issue #244 for more info.

2020-04-21 18:22 UTC, annakrystalli commented on _events/workshop-2020-05-14-remote-reprohack.md
> +eventbrite_id: https://www.eventbrite.co.uk/e/remote-reprohack-tickets-102069657092
Done in https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/pull/243/commits/2b3972e7381c5e68168fd2b1a5eaca699ef85cf2

2020-04-22 12:13 UTC, willfurnass approved these changes

2020-04-22 12:13 UTC, merged