Added champions talk events
RSE-Sheffield/RSE-Sheffield.github.io pull request #308
Opened 2020-09-18 13:11 UTC by twinkarma

2020-09-21 11:36 UTC, willfurnass requested changes

2020-09-21 11:36 UTC, willfurnass commented on _events/talk-2020-09-17-singularity-hpcchampions.md
> +Twin Karmakharm gave a talk on Singualrity for HPC at the HPC Champions event. The talk gives an introduction to the Singularity container technology and experiences learned from its uses at the Univ
/s/Singualrity/Singularity/

2020-09-21 11:36 UTC, willfurnass commented on _events/talk-2020-09-17-singularity-hpcchampions.md
> +Twin Karmakharm gave a talk on Singualrity for HPC at the HPC Champions event. The talk gives an introduction to the Singularity container technology and experiences learned from its uses at the Univ
Hyperlink Singularity to https://sylabs.io/singularity/?

2020-09-21 11:36 UTC, willfurnass commented on _events/talk-2020-09-17-jade-update-hpcchampions.md
> +title: "JADE/JADE 2 Updates"
Maybe expand to "Updates on JADE and JADE 2 Tier 2 GPU-equipped HPC systems"?  Names may not be familiar to all readers.

2020-09-21 11:36 UTC, willfurnass commented
@twinkarma Suggested some minor edits; otherwise LGTM.  Cheers.

2020-09-26 18:38 UTC, twinkarma commented on _events/talk-2020-09-17-singularity-hpcchampions.md
> +Twin Karmakharm gave a talk on Singualrity for HPC at the HPC Champions event. The talk gives an introduction to the Singularity container technology and experiences learned from its uses at the Univ
Fixed in latest commit

2020-10-01 08:25 UTC, willfurnass requested changes

2020-10-01 08:25 UTC, willfurnass commented on _events/talk-2020-09-17-singularity-hpcchampions.md
> +Twin Karmakharm gave a talk on [Singualrity](https://sylabs.io/singularity/) for HPC at the HPC Champions event. The talk gives an introduction to the Singularity container technology and experiences
Typo ('Singualrity')

2020-10-19 13:25 UTC, willfurnass approved these changes

2020-10-19 13:35 UTC, merged