Add draft blog post on container security
RSE-Sheffield/RSE-Sheffield.github.io pull request #367
Opened 2021-01-20 18:02 UTC by davidwilby

Still in draft but pretty much ready to go. Copy editing appreciated.

2021-01-21 09:24 UTC, bobturneruk approved these changes
Brilliant to have this great solution as a point of reference!

2021-01-21 09:24 UTC, bobturneruk commented on _posts/2021-01-21-github-container-security.md
> +
Extra full stop.

2021-01-21 09:24 UTC, bobturneruk commented on _posts/2021-01-21-github-container-security.md
> +5. Then build and push the images just as we did before, overwriting any previous images with those tags.
What's the mapping between git version tags and docker image versions - it looks like you can have multiple docker images for a single git version? Is this OK?

2021-01-21 09:24 UTC, bobturneruk commented on _posts/2021-01-21-github-container-security.md
> +As a result, it becomes ever more relevant to be able to automatically manage our images and perform tasks such as keeping up to date images available in an image registry, or scanning them for poten
I've heard the term "immutable infrastructure" used to describe this kind of setup. Consider using it here?

2021-01-22 09:44 UTC, davidwilby commented on _posts/2021-01-21-github-container-security.md
> +5. Then build and push the images just as we did before, overwriting any previous images with those tags.
There will only be one image tagged with a particular tag (from a tagged commit, eg `v0.1` or `latest`). When you push something with a tag that's already applied to an image in the repo, the tag is only applied to the most recent image and removed from the old one.

good question, will clarify this in the blog.

2021-01-22 09:46 UTC, davidwilby commented on _posts/2021-01-21-github-container-security.md
> +As a result, it becomes ever more relevant to be able to automatically manage our images and perform tasks such as keeping up to date images available in an image registry, or scanning them for poten
Cool, I hadn't heard this terminology before.

2021-01-26 12:02 UTC, davidwilby commented
@willfurnass If you have any feedback before we merge, I'd appreciate your perspective. But no problem if not!

2021-01-26 12:07 UTC, willfurnass commented
@davidwilby Yes, keen to review as this will be discoverable forever more.

2021-02-01 13:55 UTC, willfurnass requested changes
This is already a great post and contains some really good content.  I've made some minor suggestions but also have a couple of more general comments:

 1. I think the text would really benefit from one or more accompanying diagrams showing the workflow's various platforms, triggers/events etc.

 1. It might be helpful to more clearly separate out the general challenges from the case study.  E.g.
     1. Value of containers
     1. Inc that instantiated from static images - easy to share and reason about
     1. Security implications of working with static images: cannot deploy and forget about; more siginificant for services; even more sigificant for services exposed to public/Internet
     1. Yet many container tutorials do not offer guidance on maintaining containerised services throughout their lifecycle 
     1. What, at the highest level, is meant by vulnerabilities here?  Could note that can identify (known) bad versions of OS and language-specific packages and might need multiple tools for scanning.
     1. Checks for taking action: on new image creation and periodic
     1. Action following checks: deploy containers from updated images 
     1. Value of automation and notifications
     1. *Then* move on to case study inc workflow diagram

Both are just suggestions but might help readers identify the general challenges and decide how to adapt the workflow to suit their needs.

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +Containers (i.e. more often than not, Docker containers) continue to become an increasingly popular tool in research software. As a useful approach for many tasks, including (but not limited to) isol
Maybe 'for managing, sharing and provisioning research software' instead of 'in research software'?

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +As a result, it becomes ever more relevant to be able to automatically manage our images and perform tasks such as keeping up to date images available in an image registry, or scanning them for poten
Maybe add '(DockerHub or similar) after 'registry'?  Some may be more familiar with DockerHub as a name than image registries as a term.

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +Not least because of 2020's [attacks on HPC clusters](blog/2020-05-20-ssh-best-prac/) - it is vital to take a defensive approach to any web-exposed software. Especially those that grant any access to
"look after the updates ourselves." -> because ITS' auto-updating mechanism only affects OS packages on the Docker host and has no visibility of what packages / packages versions can be found in running containers.

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +It's perhaps beyond the scope of this blog post, but in brief, containers can be thought of as being a bit more than a virtual environment and a bit less than a virtual machine, running like a little
'virtual environment' - could clarify that mean Python virtual environments or similar.

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +GitHub launched a container registry service in September 2020, as part of their packages feature. Whilst [DockerHub](https://hub.docker.com/) is the most common registry for docker images, for this
'cheap-skate route'.  Ha.  Funny but true.

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +In contrast to some other cloud CI systems (eg GitLab, Travis, CircleCI, Appveyor [etc etc etc](https://github.com/ligurio/awesome-ci)) - GitHub actions is styled around plug-in style "actions" which
Worth adding something about only using trusted actions given they are being used to generate our main image?

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +There are more features to this action, such as building an image from a different location in the repository, well documented on the action's [marketplace page](https://github.com/marketplace/action
Consistently using camel-case for Actions could avoid any ambiguity

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +* The alerting is simple to manage, GitHub just emails me and other maintainers when an action fails. We don't have to setup any mail systems from our own infrastructure.
Not strictly true: we need email alerts (from cron on our VM) for failures to pull down new images and re-create our compose stack

2021-02-01 13:55 UTC, willfurnass commented on _posts/2021-01-21-github-container-security.md
> +Each Docker image is denoted by a name and a tag. For instance `python:3.8` is an [official Python image](https://hub.docker.com/_/python) on DockerHub, with `3.8`, the image tag, indicating the Pyth
Could add a side note that should work with / build upon trusted base images wherever possible i.e. not just pull and trust random images from public registries.

2021-02-01 14:24 UTC, willfurnass commented
Another thing that could be added, as discussed in person earlier, is a note that as an institution we're likely to move towards having funding models and processes that allow us to more easily consume cloud resource and may also have instution-supported platforms on-prem for image registry services, container orchestrators etc but until then...

2021-02-03 17:27 UTC, davidwilby commented
First pass at a diagram to go with this, although I kind of hate it for now

![image](https://user-images.githubusercontent.com/24752124/106785204-0e158500-6645-11eb-8bf8-6131f2b1b02d.png)

2022-08-10 15:35 UTC, closed without merging