Added projects Twin's involved in
RSE-Sheffield/RSE-Sheffield.github.io pull request #390
Opened 2021-02-22 13:47 UTC by twinkarma

The GATE projects don't really map well to the fundings:
* The rumour veracity span all 3 fundings if I remember correctly
* It's only been the rumour veracity project that I was working with @davidwilby, otherwise I might be on the same funding but was working on totally different things from @davidwilby and @drj11. @bobturneruk , any guidelines on a good way to present this?

2021-02-22 15:19 UTC, bobturneruk commented
>...the same funding but was working on totally different things from @davidwilby and @drj11. @bobturneruk , any guidelines on a good way to present this?

I think we want to be breaking down by "project" rather than "funding source".

2021-02-22 15:20 UTC, bobturneruk commented
It could be that the existing list is useless in some cases, o feel free to change it. Linking back to rse-admin is not important.

2021-02-23 10:42 UTC, twinkarma commented
No problem. I'd thought that might be the case but just wanted clarification on it.

2021-02-26 14:54 UTC, willfurnass commented on _project_descriptions/basisflow.md
> +Basisflow is a computational chemistry project that aims to apply machine learning approach to the generation of basis sets, mathematical functions used in the representation of atomic and molecular
Could link to https://gow.epsrc.ukri.org/NGBOViewGrant.aspx?GrantRef=EP/T027134/1 and/or http://www.grant-hill.group.shef.ac.uk/

2021-02-26 14:55 UTC, willfurnass commented on _project_descriptions/jade2.md
> +JADE II is a Deep Learning focused, newly launched Tier-2 HPC system associated with 19 academic partners including Sheffield.
Could emphasise that architected to meet the needs of DL + molecular dynamics folks.

2021-02-26 14:55 UTC, willfurnass commented on _project_descriptions/jade2.md
> +JADE II is a Deep Learning focused, newly launched Tier-2 HPC system associated with 19 academic partners including Sheffield.
And possibly say is a successor to https://www.jade.ac.uk/

2021-02-26 14:56 UTC, willfurnass commented on _project_descriptions/rumour_varacity.md
> +key: rumour_varacity
s/varacity/veracity/ ?

2021-02-26 14:56 UTC, willfurnass commented on _project_descriptions/rumour_varacity.md
> +The Rumour Varacity project provides a [web-based platform]((https://tweetveracity.gate.ac.uk/)) for automatically identifying rumours in social media and assessing their veracity. The project featur
s/Varacity/Veracity/ ?

2021-02-26 14:57 UTC, willfurnass commented on _project_descriptions/rumour_varacity.md
> +RSES is involved in the development of the entire service stack including the development of the web GUI and the server back-end for deploying the deep learning models.
Worth mentioning the automatic retraining if that's particularly novel?

2021-02-26 14:59 UTC, willfurnass commented on _data/projects.csv
> +id,key,title,long_title,tech_methods,rses,start,end,department,level,show
Odd that all lines marked as having changed?

2021-02-26 14:59 UTC, willfurnass commented on _data/projects.csv
> +7, bbsrc_chaste,BBSRC: Cell Modelling,BBSRC: Cell Modelling,,Twin Karmakharm,01/10/2018,30/09/2021,Mathematics and Statistics,2,1
What about tags for chaste?  C++?

2021-02-26 15:03 UTC, willfurnass commented on _data/projects.csv
> +40, jade2,JADE II Support,JADE II Support,,"Anna Krystalli, Twin Karmakharm",01/02/2020,01/08/2021,IT Services,2,1
Tags for JADE?

2021-02-26 15:04 UTC, willfurnass commented on _data/projects.csv
> +10,,Google DNI Journalist,Google DNI Journalist,,"David Jones, Twin Karmakharm",01/01/2019,01/01/2020,Computer Science,2,1
Tags?

2021-02-26 15:04 UTC, willfurnass commented on _data/projects.csv
> +32,,SoBigData++,SoBigData++,,"David Jones, Twin Karmakharm",01/01/2020,01/01/2022,Computer Science,2,1
Tags?

2021-02-26 15:04 UTC, willfurnass commented on _data/projects.csv
> +33,,RISIS II (includes WeVerfiy and some ELG),RISIS II (includes WeVerfiy and some ELG),,"Twin Karmakharm, David Wilby",01/01/2020,30/06/2021,Computer Science,2,1
Tags?

2021-02-26 15:05 UTC, willfurnass commented on _data/projects.csv
> +58, ratesetter,RateSetter / Merseyrail,RateSetter / Merseyrail,,Twin Karmakharm,18/11/2019,01/12/2020,Mechanical Engineering,2,1
Tags

2021-02-26 15:05 UTC, willfurnass commented on _data/projects.csv
> +45, basisflow,BasisFlow,BasisFlow,,Twin Karmakharm,01/01/2021,31/12/2023,Chemistry,2,1
Tags

2021-02-26 15:05 UTC, willfurnass commented on _project_descriptions/rumour_varacity.md
> +RSES is involved in the development of the entire service stack including the development of the web GUI and the server back-end for deploying the deep learning models.
Could add more about tech and methods used?

2021-02-26 15:06 UTC, willfurnass commented on _project_descriptions/ratesetter.md
> +RSE was involved in the creation of the [FLAME GPU](http://www.flamegpu.com/)-based pedestrian model that simulates passengers boarding and alighting the train which is used as a basis for predicting
Any tech challenges worth mentioning e.g. performance?

2021-02-26 15:07 UTC, willfurnass commented on _project_descriptions/bbsrc_chaste.md
> +Development project contributing to the development and optimisation of the [Chaste](https://www.cs.ox.ac.uk/chaste/cell_based_index.html) cell modelling software. In particular, the addition a new f
Could make more of challenges and success of integrating new tested functionality in a large, mature existing codebase?

2021-02-26 15:07 UTC, willfurnass requested changes
Made various suggestions.

2021-03-01 14:19 UTC, twinkarma commented on _data/projects.csv
> +id,key,title,long_title,tech_methods,rses,start,end,department,level,show
I'd had to do a re-merge since master was updated and it might have happened then.

2021-03-01 14:47 UTC, twinkarma commented on _project_descriptions/jade2.md
> +JADE II is a Deep Learning focused, newly launched Tier-2 HPC system associated with 19 academic partners including Sheffield.
Fixed in push

2021-03-01 14:47 UTC, twinkarma commented on _project_descriptions/rumour_varacity.md
> +key: rumour_varacity
Fixed in push

2021-03-01 14:47 UTC, twinkarma commented on _project_descriptions/rumour_varacity.md
> +The Rumour Varacity project provides a [web-based platform]((https://tweetveracity.gate.ac.uk/)) for automatically identifying rumours in social media and assessing their veracity. The project featur
Fixed in push

2021-03-01 14:47 UTC, twinkarma commented on _data/projects.csv
> +id,key,title,long_title,tech_methods,rses,start,end,department,level,show
Fixed in push

2021-03-01 14:47 UTC, twinkarma commented on _data/projects.csv
> +7, bbsrc_chaste,BBSRC: Cell Modelling,BBSRC: Cell Modelling,,Twin Karmakharm,01/10/2018,30/09/2021,Mathematics and Statistics,2,1
Fixed in push

2021-03-01 14:47 UTC, twinkarma commented on _data/projects.csv
> +10,,Google DNI Journalist,Google DNI Journalist,,"David Jones, Twin Karmakharm",01/01/2019,01/01/2020,Computer Science,2,1
Fixed in push

2021-03-01 14:48 UTC, twinkarma commented on _data/projects.csv
> +33,,RISIS II (includes WeVerfiy and some ELG),RISIS II (includes WeVerfiy and some ELG),,"Twin Karmakharm, David Wilby",01/01/2020,30/06/2021,Computer Science,2,1
Fixed in push

2021-03-01 14:48 UTC, twinkarma commented on _data/projects.csv
> +32,,SoBigData++,SoBigData++,,"David Jones, Twin Karmakharm",01/01/2020,01/01/2022,Computer Science,2,1
Fixed in push

2021-03-01 14:48 UTC, twinkarma commented on _data/projects.csv
> +45, basisflow,BasisFlow,BasisFlow,,Twin Karmakharm,01/01/2021,31/12/2023,Chemistry,2,1
Fixed in push

2021-03-01 14:48 UTC, twinkarma commented on _data/projects.csv
> +58, ratesetter,RateSetter / Merseyrail,RateSetter / Merseyrail,,Twin Karmakharm,18/11/2019,01/12/2020,Mechanical Engineering,2,1
Fixed in push

2021-03-01 14:48 UTC, twinkarma commented on _project_descriptions/bbsrc_chaste.md
> +Development project contributing to the development and optimisation of the [Chaste](https://www.cs.ox.ac.uk/chaste/cell_based_index.html) cell modelling software. In particular, the addition a new f
Added this in push

2021-03-01 14:51 UTC, twinkarma commented on _project_descriptions/ratesetter.md
> +RSE was involved in the creation of the [FLAME GPU](http://www.flamegpu.com/)-based pedestrian model that simulates passengers boarding and alighting the train which is used as a basis for predicting
Not much new on the modelling side, just the optimisation which was done by the other team.

2021-03-01 14:51 UTC, twinkarma reviewed
Implemented recommended changes.

2021-03-01 15:13 UTC, willfurnass approved these changes
See minor suggestions in stand-alone comments (sorry, forgot to make them part of this Review.  Otherwise LGTM.

2021-03-01 15:15 UTC, merged

2021-03-01 15:16 UTC, twinkarma commented
Thanks for your review @willfurnass