Newsletter 2021 03
RSE-Sheffield/RSE-Sheffield.github.io pull request #415
Opened 2021-03-05 12:40 UTC by twinkarma

2021-03-08 13:37 UTC, willfurnass requested changes
Made some small suggestions but otherwise looks good.  Looks like the main thing to address before this goes out is the info on the next LB event.

2021-03-08 13:37 UTC, willfurnass commented on .gitignore
> +.idea/
Some things unrelated to IDEA removed from this - sure you wanted to delete them?

2021-03-08 13:37 UTC, willfurnass commented on _newsletters/2021-03-10-newsletter.md
> +The **[UKRN Academy](https://www.ukrn.org/ukrn-academy/)** forum was created for doctoral students working on reproducibility and metascience projects. It is a part of the [UK Reproducibility Network
Worth adding that:
 - The UKRN contact for the Academy is Tom Stafford, institutional lead for the University of Sheffield.
 - One PhD student at Sheffield;  focussing on *Evaluating the perceptions of bias, replication and transparency in evolution and climate change science*; co-supervised by Andrew Beckerman and @annakrystalli

2021-03-08 13:37 UTC, willfurnass commented on _newsletters/2021-03-10-newsletter.md
> +The **Reprohack NL** team have won this year's **[Open Initiative Trophy](https://opensciencefestival.nl/the-open-initiative-trophies/)**. We'd like to congratulate the team including Anna Krystalli
Any future reprohacks to promote here @annakrystalli ?

2021-03-08 13:37 UTC, willfurnass commented on _newsletters/2021-03-10-newsletter.md
> +**Upcoming [N8 CIR](https://n8cir.org.uk/) training events:**
Could also add https://n8cir.org.uk/news/cuda-cc-fundamentals/ if it's not sold out yet

2021-03-08 13:37 UTC, willfurnass commented on _newsletters/2021-03-10-newsletter.md
> +The **next LunchBytes event** will be in early to mid March, with a provisional theme of **Making GPU programming more accessible**.
Re the next LB: @MILeach have you got a new date in mind and can any details of talks/speakers be shared?

2021-03-08 13:37 UTC, willfurnass commented on _newsletters/2021-03-10-newsletter.md
> +**[Introduction to Data Science online-book](https://rafalab.github.io/dsbook/)** covers a wide range of data science topics including [machine learning](https://rafalab.github.io/dsbook/introduction
```suggestion
**[Introduction to Data Science online book](https://rafalab.github.io/dsbook/)** covers a wide range of data science topics including [machine learning](https://rafalab.github.io/dsbook/introduction-to-machine-learning.html). Practical examples are provided in R.
```

2021-03-08 13:37 UTC, willfurnass commented on _newsletters/2021-03-10-newsletter.md
> +Need access to managed desktop software? The University provides a **[find a pc website](https://www.sheffield.ac.uk/findapc/now)** to gives students remote access to PCs running University Desktop.
```suggestion
Need access to managed desktop software? The University provides a **[Find A PC website](https://www.sheffield.ac.uk/findapc/now)** to gives students remote access to PCs running University Desktop.
```

2021-03-09 16:11 UTC, Robadob reviewed
Looks good, I agree with most of the points that Will has already raised.

2021-03-10 12:05 UTC, MILeach commented on _newsletters/2021-03-10-newsletter.md
> +The **next LunchBytes event** will be in early to mid March, with a provisional theme of **Making GPU programming more accessible**.
Sorry have only just seen this - it will be in the last week of March, looking very likely to be Thursday 1st April, but I'm still waiting on confirmation from the 3rd speaker that this date is good for him. It's also likely to be a "late lunch" from 2-3pm as one of our speakers is from Texas! 

Speakers will be:
Freddie Witherden (https://engineering.tamu.edu/ocean/profiles/witherden-freddie.html), developer of PyFR, a CUDA accelerated python CFD library

James Knight (https://profiles.sussex.ac.uk/p415734-james-knight), developer of PyNN/GeNN, a GPU enhanced Neuronal Network simulation environment

(Waiting on confirmation of date) Tom Deakin (https://research-information.bris.ac.uk/en/persons/tom-deakin), works on understanding performance portability of parallel codes across different programming languages

I would suggest perhaps including the list of speakers but leaving the date at week commencing 29th March for now. I can send an update round when it is confirmed.

2021-03-11 14:58 UTC, twinkarma commented on .gitignore
> +.idea/
I'll revert it in the next commit

2021-03-11 14:58 UTC, twinkarma commented on _newsletters/2021-03-10-newsletter.md
> +The **[UKRN Academy](https://www.ukrn.org/ukrn-academy/)** forum was created for doctoral students working on reproducibility and metascience projects. It is a part of the [UK Reproducibility Network
* Adding contact's a good idea
* Not sure about mentioning specific PhD student though?

2021-03-11 14:58 UTC, twinkarma commented on _newsletters/2021-03-10-newsletter.md
> +The **next LunchBytes event** will be in early to mid March, with a provisional theme of **Making GPU programming more accessible**.
I've added confirmed speakers and changed the date to "early April"

2021-03-11 17:12 UTC, willfurnass approved these changes

2021-03-11 17:12 UTC, willfurnass commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
What's this?

2021-03-12 11:36 UTC, twinkarma commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
It's an IDE feature that performs code inspection?

2021-03-12 11:38 UTC, merged