clarifications, corrections and improvements to lunchbytes page
RSE-Sheffield/RSE-Sheffield.github.io pull request #449
Opened 2021-04-21 14:52 UTC by davidwilby

2021-04-21 15:04 UTC, willfurnass requested changes

2021-04-21 15:04 UTC, willfurnass commented on pages/community/lunch-bytes.md
> +Each LunchBytes session features several related short talks on a theme (each being ~10 mins) rather than one longer talk - followed by a dicussion session.
Agree that it's not worth making comparisons to our seminar series any more.

s/features/typically features/

sp of 'dicussion'

2021-04-21 15:04 UTC, willfurnass commented on pages/community/lunch-bytes.md
> +## Recordings of previous LunchBytes
Do we want to start adding links to recordings here in addition to the per-session pages?  Also, if we really do want to do this do we need to update the operations guide?

2021-04-22 10:03 UTC, davidwilby commented on pages/community/lunch-bytes.md
> +## Recordings of previous LunchBytes
I'm not sure we want all of them here  - maybe we do? I at least wanted a few as a way of making them more visible.

2021-04-22 10:25 UTC, willfurnass commented on pages/community/lunch-bytes.md
> +## Recordings of previous LunchBytes
Okay, seems reasonable, provided we have a prompt to remind us to append to this list per event.

2021-04-22 10:26 UTC, willfurnass approved these changes

2021-04-22 10:33 UTC, davidwilby commented on pages/community/lunch-bytes.md
> +## Recordings of previous LunchBytes
I'll add something to the guidance

2021-04-22 10:33 UTC, merged