Collaboration
RSE-Sheffield/RSE-Sheffield.github.io pull request #532
Opened 2022-01-24 16:40 UTC by bobturneruk

Re words and re expresses what we do in terms of collaboration, rather than service.

2022-01-24 16:42 UTC, bobturneruk commented
This will need specific approval from @mondus, but all feedback is appreciated. Have I messed up the Jekyll?

2022-01-24 16:44 UTC, mondus commented on _data/navigation.yml
> +- title: Work With RSEs
```suggestion
- title: The RSE Collaborative Model
```
It needs to give the impression that we do/deliver something (without using the word service)

2022-01-24 16:48 UTC, mondus commented on _layouts/home.html
> +                    People who work on research software may chose to call themselves Research Software Engineers (RSEs). The RSE Team engages and collaborates with University of Sheffield researcher
```suggestion
                    Research Software Engineering is the practice of engineering software to facilitate better research. People who work on research software may chose to call themselves Research Software Engineers (RSEs). The RSE Team provides a centrally supported group to embed this expertise across the portfolio of the University of Sheffield research and to support the practise of Research Software Engineering more broadly.
```

2022-01-24 16:50 UTC, mondus requested changes
Made a couple of changes to the homepage text as I don't want to loose the fact that we support the practice of Research Software Engineering.

2022-01-24 17:13 UTC, bobturneruk commented on _layouts/home.html
> +                    People who work on research software may chose to call themselves Research Software Engineers (RSEs). The RSE Team engages and collaborates with University of Sheffield researcher
Makes sense. I'll see how it renders...

2022-01-24 17:15 UTC, bobturneruk commented on _layouts/home.html
> +                    People who work on research software may chose to call themselves Research Software Engineers (RSEs). The RSE Team engages and collaborates with University of Sheffield researcher
I think it needs to be more concise:

![image](https://user-images.githubusercontent.com/34244196/150831641-c0733625-04e2-42f4-ab22-a97ebe366849.png)

2022-01-24 17:17 UTC, bobturneruk commented on _data/navigation.yml
> +- title: Work With RSEs
I want the link to be a call to action - for people to look at the home page and go "What's next?" and then click it. It could be "Collaborate"?

2022-01-26 11:54 UTC, mondus commented on _data/navigation.yml
> +- title: Work With RSEs
Yes just collaborate would work

2022-01-26 11:57 UTC, mondus commented on _layouts/home.html
> +                    People who work on research software may chose to call themselves Research Software Engineers (RSEs). The RSE Team engages and collaborates with University of Sheffield researcher
Your right but we need to keep the emphasis on both us a centrally support group of RSE practitioners and their also being a community of people who do RSE.

"The RSE Team provides a centrally supported group to embed RSE professionals across the portfolio of the University of Sheffield research as well as support the practise of RSE more broadly."

2022-01-26 12:29 UTC, bobturneruk commented
![image](https://user-images.githubusercontent.com/34244196/151163128-a2cf0cc1-f915-46cd-ab7b-eb2a6ad98d0c.png)

Another iteration. Whay do you think @mondus?

2022-01-28 09:47 UTC, mondus approved these changes
Happy with this

2022-01-28 09:51 UTC, merged