Handbook
RSE-Sheffield/RSE-Sheffield.github.io pull request #550
Opened 2022-03-08 10:24 UTC by mondus

Adds the RSE Working Practice document to the website. Note: I have not built this locally.

2022-03-08 11:21 UTC, davidwilby requested changes

2022-03-08 11:21 UTC, davidwilby commented on pages/collaboration/handbook/handbook.md
> +### Issues & Project Boards {#issues-&-project-boards}
the `&` causes this to render the contents of the curly braces, change to `{#issues-and-project-boards}` or something without the ampersand

2022-03-08 11:21 UTC, davidwilby commented on pages/collaboration/handbook/handbook.md
> +The RSE team delivers code according to best practises using a collaborative version control system (preferably GitHub, but equivalent tools such as GitLab or Bitbucket can be used for established pr
practises -> practices

2022-03-08 11:21 UTC, davidwilby commented on pages/collaboration/handbook/handbook.md
> +
Would it be possible to have a table of contents? (can be left for a future PR though)

2022-03-08 11:21 UTC, davidwilby commented
There's a potential name clash within the team for the term 'handbook', though not confusing on the website itself. If you wanted to, could change the name of this to 'collaboration guide' or something.

2022-03-08 17:28 UTC, mondus commented on pages/collaboration/handbook/handbook.md
> +
Probably but not sure how. Would rather megre and then do this as a new PR.

2022-03-08 17:29 UTC, mondus commented on pages/collaboration/handbook/handbook.md
> +The RSE team delivers code according to best practises using a collaborative version control system (preferably GitHub, but equivalent tools such as GitLab or Bitbucket can be used for established pr
```suggestion
The RSE team delivers code according to best practices using a collaborative version control system (preferably GitHub, but equivalent tools such as GitLab or Bitbucket can be used for established projects). At the outset of the project initial code can be provided on a secure shared resource like Google Drive however we would expect to migrate this to version control to make any changes. The RSE team can help you to do this. If you already use version control and have a private repository, you will need to add the allocated RSE as a collaborator.
```

2022-03-08 17:30 UTC, mondus commented on pages/collaboration/handbook/handbook.md
> +### Issues & Project Boards {#issues-&-project-boards}
```suggestion
### Issues and Project Boards {#issues-and-project-boards}
```

2022-03-22 09:48 UTC, mondus commented on pages/collaboration/handbook/handbook.md
> +### Issues & Project Boards {#issues-&-project-boards}
Changes made

2022-03-22 09:49 UTC, mondus commented on pages/collaboration/handbook/handbook.md
> +The RSE team delivers code according to best practises using a collaborative version control system (preferably GitHub, but equivalent tools such as GitLab or Bitbucket can be used for established pr
fixed

2022-03-22 09:49 UTC, mondus commented
Changes made and renamed as collaboration guide. @davidwilby Can you resolve if happy and give it a final check.

2022-03-22 09:52 UTC, davidwilby commented
> Changes made and renamed as collaboration guide. @davidwilby Can you resolve if happy and give it a final check.

Ha! Sorry, I was just this moment going to the website to see if this had been merged. Have resolved. LGTM

2022-03-22 09:55 UTC, davidwilby approved these changes

2022-03-22 10:33 UTC, merged