Added tier 2 call page
RSE-Sheffield/RSE-Sheffield.github.io pull request #555
Opened 2022-03-22 11:55 UTC by mondus

Adds the open tier 2 call page to the collaboration links as well as a button on the homepage (at least for the next month).

2022-03-22 12:29 UTC, twinkarma commented on pages/collaboration/tier2/tier2.md
> +## How Your Application will be Assessed (PR)
Remove (PR)

2022-03-22 12:32 UTC, twinkarma commented on pages/collaboration/tier2/tier2.md
> +
Remove all internal notes below

2022-03-22 12:35 UTC, twinkarma commented on pages/collaboration/tier2/tier2.md
> +
@frb-yousefi would you be able to help add in another case study related to your ML consultancy?

@mondus @ptheywood  Would it also be good to add a case study related to optimisation, GPU or otherwise? Do we have any examples?

2022-03-22 12:39 UTC, mondus commented on pages/collaboration/tier2/tier2.md
> +
Yes I just realised this.

2022-03-22 12:40 UTC, mondus commented on pages/collaboration/tier2/tier2.md
> +## How Your Application will be Assessed (PR)
```suggestion
## How Your Application will be Assessed
```

2022-03-22 13:21 UTC, ptheywood requested changes

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +* **Impact of the project ** (200 words): How will the embedded RSE effort change your current approach to research/experimentation.
```suggestion
* **Impact of the project** (200 words): How will the embedded RSE effort change your current approach to research/experimentation.
```

2022-03-22 13:21 UTC, ptheywood commented on _layouts/home.html
> +					<div class="social-media-inner container text-center">
This renders poorly.

![image](https://user-images.githubusercontent.com/628937/159477917-aac4879b-77c1-406e-99a3-162a908324c3.png)

You could also switch to `btn-info` if you want one of them to be blue so all 3 colours of the RSE logo are used (rather than GYG).

2022-03-22 13:21 UTC, ptheywood commented on _layouts/home.html
> +                        <a href="https://goo.gl/forms/5MVy0jM6xQhWlpmn1"
The Apply for funding button links to the code clinic form.

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +# Open Call: Funding for Embedded support for High Performance Computing and Machine Learning
The font size of this is execssive.

![image](https://user-images.githubusercontent.com/628937/159484333-0969f219-a9d4-425d-bd90-a0f26b305b9b.png)

This is a general comment on the H1 styling, but the simplest fix is to switch to `##` and increment all the heading levels on the page.

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +High performance computing (HPC) is the processing of data and performing of computing calculations at high speeds. When surveyed (as part of the Sheffield Research Software survey 2020), roughly a q
```suggestion
High performance computing (HPC) is the processing of data and performing of computing calculations at high speeds. When surveyed (as part of the Sheffield Research Software survey 2020), roughly a quarter of researchers from all faculties at Sheffield expressed an interest in using HPC in the future. It may not be as difficult as you would think to do so! The barrier to entry for using specialist HPC facilities such as Graphics Processing Units (GPUs) has been significantly lowered by the emergence of software to facilitate Machine Learning (ML) and AI. The purpose of this open call is to provide funding to support skilled Research Software Engineers (RSEs) to assist researchers in migrating their research workflows to suitable HPC systems. RSE support will be provided from the [Sheffield RSE group](https://rse.shef.ac.uk/). The RSE group is a team of 12 who provide collaborative embedded support for research across the whole of the university.
```

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +This call will specifically aim to enable researchers to use the Tier 2 HPC systems by providing funding for embedded support within research teams or with individual researchers. Embedded support wi
Previously stated it's a team of `12`, so is it `12` or `~13`?

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +This call is open to all research staff but with some conditions imposed by the Tier 2 facilities. Postdocs must have at least one year left on their contract (else should apply via their PI). Postdo
PhD students are not `postdoctoral` surely?

```suggestion
This call is open to all research staff but with some conditions imposed by the Tier 2 facilities. Postdocs must have at least one year left on their contract (else should apply via their PI). Doctoral research students must have support from their supervisor.
```

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +You should apply via the provided expression of interest google form below. This is an open call but applications will be reviewed in batches every 6 months. **The closing date for the next (first) r
```suggestion
You should apply via the provided expression of interest google form below. This is an open call but applications will be reviewed in batches every 6 months. **The closing date for the next (first) round of reviews is Friday 22/04/2022 at 17:00**. Applications received after this date will be reviewed in the next round of applications. Dates for future rounds will be announced on this page.
```

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +On receiving a completed application form we will contact you to arrange a short (less than 30m) online consultation to gather any additional technical information required to understand your project
```suggestion
On receiving a completed application form we will contact you to arrange a short (less than 30 minutes) online consultation to gather any additional technical information required to understand your project. The application form is purposefully short to ensure that we can discuss your requirements rather than expect you to provide all of these in the written application. 
```

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +[https://bit.ly/Tier2support](https://bit.ly/Tier2support)
Url shortened links are generally not great, they can take you anywhere. 

It would be better to provide meaningful link text which connects directly to the form. 

```suggestion
[Application Form](https://docs.google.com/forms/d/e/1FAIpQLScsp1T57ohGnCA91D7KoKJPPtGiuVTY52u8S3q21I9VLLsH0Q/viewform) 
```

It would be even better if this were part of the above paragraph so the link made sense in context (not sure how to do a multiline suggestion, sorry)

2022-03-22 13:21 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +# Detail to Capture and Internal Notes
This section and below should not be here?

2022-03-22 15:17 UTC, ptheywood commented on pages/collaboration/tier2/tier2.md
> +# Open Call: Funding for Embedded support for High Performance Computing and Machine Learning
Opened #558 related to this, to be resolved in the future.

2022-03-22 17:12 UTC, mondus commented on pages/collaboration/tier2/tier2.md
> +This call will specifically aim to enable researchers to use the Tier 2 HPC systems by providing funding for embedded support within research teams or with individual researchers. Embedded support wi
It literally changes mid sentence sometimes

2022-03-22 17:13 UTC, mondus commented on pages/collaboration/tier2/tier2.md
> +This call will specifically aim to enable researchers to use the Tier 2 HPC systems by providing funding for embedded support within research teams or with individual researchers. Embedded support wi
```suggestion
This call will specifically aim to enable researchers to use the Tier 2 HPC systems by providing funding for embedded support within research teams or with individual researchers. Embedded support will be provided by the Research Software Engineering group, a team of ~12 software engineering experts who work collaboratively across the entire university supporting [~40 active projects](https://rse.shef.ac.uk/collaboration/projects/) worth over £12M to the university. The call is keen to support researchers from a diverse research background, particularly those who are not traditional HPC users.
```

2022-03-24 20:09 UTC, mondus commented on pages/collaboration/tier2/tier2.md
> +
Need to get this out so later examples can follow

2022-03-24 20:16 UTC, ptheywood approved these changes

2022-03-25 14:23 UTC, twinkarma approved these changes

2022-03-28 17:43 UTC, merged