Matlab reproducibility blog
RSE-Sheffield/RSE-Sheffield.github.io pull request #579
Opened 2022-04-29 11:46 UTC by davidwilby

Possibly oversized blog for your delectation. Any and all feedback gratefully received.

Also adds github-style emoji support to the site, can remove or put in different PR if required

2022-04-29 12:10 UTC, ns-rse commented on _posts/2022-05-05-reproducible-matlab.md
> +Therefore, you need to write your documentation in a format that can be handled by your version control system (most likely, `git`) - e.g. as text files, and not a PDF, word document or google doc. A
Typo...

```suggestion
Therefore, you need to write your documentation in a format that can be handled by your version control system (most likely, `git`) - e.g. as text files, and not a PDF, word document or google doc. A number of tools exist for doing this outside of Matlab, be it [read the docs](https://readthedocs.org/), [roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html) or another documentation generator.
```

2022-04-29 12:14 UTC, ns-rse commented on _posts/2022-05-05-reproducible-matlab.md
> +At the time of writing, there is one answer to this question, namely `git`. Developed in 2006, `git` has become the _de facto_ standard VCS and for many developers is synonymous with the concept. As
Could perhaps link to the git site?

```suggestion
At the time of writing, there is one answer to this question, namely [`git`](https://git-scm.com). Developed in 2006, `git` has become the _de facto_ standard VCS and for many developers is synonymous with the concept. As a researcher you may, however, come across older codebases controlled with other systems such as Subversion (SVN), but `git` is the way to go for new projects at present.
```

2022-04-29 12:19 UTC, ns-rse commented on _posts/2022-05-05-reproducible-matlab.md
> +It would be irresponsible to attempt to provide instruction on using `git` here and there are many resources to learn from, not least the courses run by RSE teams!
Perhaps link to the courses page..

```suggestion
It would be irresponsible to attempt to provide instruction on using `git` here and there are many resources to learn from, not least the [courses](https://rse.shef.ac.uk/events/) run by RSE teams!
```

2022-04-29 15:28 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +During my PhD and postdoctoral research, I used MATLAB, among other languages, to analyse data, run simulations, make figures and control instrumentation. However, at the time, I didn't know about th
> For the last few years, as a Research Software Engineer, I've gained...

Something about this reads weirdly, replacing `For` with `Over` fixes it, can't pin down the exact cause in my mind though. 🤷‍♂️

2022-04-29 15:33 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +During my PhD and postdoctoral research, I used MATLAB, among other languages, to analyse data, run simulations, make figures and control instrumentation. However, at the time, I didn't know about th
agreed!
```suggestion
During my PhD and postdoctoral research, I used MATLAB, among other languages, to analyse data, run simulations, make figures and control instrumentation. However, at the time, I didn't know about the concepts required to make my code reproducible for myself and others. Over the last few years, as a Research Software Engineer, I've gained the experience needed to develop reproducible software in a range of languages including MATLAB. Now it's time to share what I've learned with everyone!
```

2022-04-29 15:34 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +## What is reproducibility?
You're very inconsistent with using title-case throughout the page.

2022-04-29 15:36 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +1. Include comments that explain what your code is doing,
Some of your list items end in commas, one ends in a bullet point. Be consistent.

2022-04-29 15:37 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +1. Include comments that explain what your code is doing,
p.s. numbering everything `1.` is upsetting, but i guess markdown doesn't care.

2022-04-29 15:40 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +├── output/
what's the purpose of `output/`, my initial thought was that `data/` would be raw/processed output data (working with modelling I can generate a ton of data from tiny inputs, but maybe the answer to this question would be obvious to a matlab user).

2022-04-29 15:42 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +Your users will thank you (that includes you) when they encounter some actual guidance on how to use your code - maybe they'll actually use it! Imagine that!
maybe emphasize the "that includes you" part with italics/bolds. It's a really important point that people forget.

2022-04-29 15:42 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +1. Include comments that explain what your code is doing,
will do, thanks for the spot

2022-04-29 15:51 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +Therefore, you need to write your documentation in a format that can be handled by your version control system (most likely, `git`) - e.g. as text files, and not a PDF, word document or google doc. A
Or just latex if you're a hardcore academic who loves to write some tex.

2022-04-29 15:53 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +Therefore, you need to write your documentation in a format that can be handled by your version control system (most likely, `git`) - e.g. as text files, and not a PDF, word document or google doc. A
Arguably many may be more comfortable writing documentation in tex, which they're already familiar with, than learning rst.

2022-04-29 16:01 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +#### Why use version control?
Logically it makes more sense to tell people WHY to use VC, as this involves explaining what VC is, before explaining which VCS they should be using.

I'd swap this section with the prior. Just be careful of your acronyms.

2022-04-29 16:03 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +At the time of writing, there is one answer to this question, namely [`git`](https://git-scm.com). Developed in 2006, `git` has become the _de facto_ standard VCS and for many developers is synonymou
Subversion, mercurial, Gnu bazaar are possible the 3 prior biggest from my experience.

2022-04-29 16:05 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +Version control allows you to capture snapshots of your code as you develop (in `git` these are called **commits**), meaning that you can go back if you want to. Furthermore, you can create _branches
> exploratory branch

Not heard that before, it's normally feature branch

2022-04-29 16:15 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +MATLAB provides tools for [class-based testing](https://uk.mathworks.com/help/matlab/class-based-unit-tests.html); [testing applications](https://uk.mathworks.com/help/matlab/app-testing-framework.ht
> [class-based testing](https://uk.mathworks.com/help/matlab/class-based-unit-tests.html)

This is misleading.

The previous section is "Function-based testing"

> If your code is organised into functions, you can use the function-based testing framework to test those functions with a test suite.

`function-based unit testing` and` class-based unit testing`, refer to the MatLab interface for writing tests, not what is being tested you can test functions and classes with both. This is made clear by one of the of the links from the `class-based testing` page: https://uk.mathworks.com/help/matlab/matlab_prog/write-simple-test-case-using-classes.html

2022-04-29 16:19 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +* Continue working with the new changes and repeat!
Using the appropriate default `.gitignore` ?: https://github.com/github/gitignore/blob/main/Global/MATLAB.gitignore

I see alot of python users committing the junk `__pycache__` files bc they don't use a git ignore.

2022-04-29 16:21 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +In brief, GitHub actions is a really, really, _really_ useful tool! Some examples of things I've done with them with MATLAB are: running tests when a pull request is made so that we can see that the
> GitHub actions is
are*

2022-04-29 16:22 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +In brief, GitHub actions is a really, really, _really_ useful tool! Some examples of things I've done with them with MATLAB are: running tests when a pull request is made so that we can see that the
> I've done with them with MATLAB are

with them when using MATLAB

with them with reads badly

2022-04-29 16:25 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +  * run MATLAB's [`checkcode` function](https://uk.mathworks.com/help/matlab/ref/checkcode.html) against the repo to look for problems in the code so you don't have to look for them manually?
The question marks on these 3 items are an unusual choice.

2022-04-29 16:25 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +  * run MATLAB's [`checkcode` function](https://uk.mathworks.com/help/matlab/ref/checkcode.html) against the repo to look for problems in the code so you don't have to look for them manually?
My initial thought was, is this list still in the todo stage.

2022-04-29 16:28 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +These can be run on GitHub actions' cloud computing for free for _public_ projects hosted on GitHub (just another reason to go open source! :grinning:), but if your project is private, you can still
You get a free amount of minutes/month for private repos (accounted on an org/user basis). Possibly viable for MatLab CI where jobs are very fast running as nothing needs to be installed?

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

2022-04-29 16:31 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +**Note** the application must be built for each operating system (Windows, Mac OS, Linux etc) and generally the build must be run on a compatible operating system. For instance, if you want to build
>if you want to build your program to run on Windows, the build should be run from within Matlab on Windows.

Reword this, "the build should be run" reads asthough the built executable, rather than the compilation. (I'm used to seeing build refer to the results of the compilation/build process.)

2022-04-29 16:33 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +By hosting your code on a public repository with a tool like GitHub, you'll be able to link to the code as it was at the time of submission. At this stage, I'd recommend creating a tag to indicate th
zenodo to create a doi for the tag?

https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

2022-04-29 16:34 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +Just try your best! Most researchers still don't publish their code and very few are reproducible, so anything you can do to improve your work will get you closer.
very few what? The implication is researchers not code imo.

2022-04-29 16:41 UTC, Robadob requested changes
Rework the testing section. Fairly sure you've made a glaring error regarding `function-based` and `class-based` testing see the in-line comment.

Rename the function-based section unit testing, explain the concept, say matlab offers x and y, demonstrate the one you prefer, link the other.

I'm not sure of a proper name for your 'script-based testing'. I've written code heavy in assertions (most of the fgpu2 visualiser), just seems like general validation for producing a robust program.

Otherwise the article is great, remaining comments are the usual minor copy-edit stuff.

2022-05-03 08:04 UTC, davidwilby commented
Thanks for the massive feedback/proof-reading @Robadob - I'll address these. Cheers!

2022-05-03 08:12 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +These can be run on GitHub actions' cloud computing for free for _public_ projects hosted on GitHub (just another reason to go open source! :grinning:), but if your project is private, you can still
In this case, the Matlab github actions themselves aren't allowed to be run on GH hosted runners if the repo is private. Will clarify.

2022-05-03 08:14 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +  * run MATLAB's [`checkcode` function](https://uk.mathworks.com/help/matlab/ref/checkcode.html) against the repo to look for problems in the code so you don't have to look for them manually?
> My initial thought was, is this list still in the todo stage.

As a result of the question marks? Or because it's a short list?

2022-05-03 08:16 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +In brief, GitHub actions is a really, really, _really_ useful tool! Some examples of things I've done with them with MATLAB are: running tests when a pull request is made so that we can see that the
> > GitHub actions is
> 
> are*

GitHub actions when referring to the overall product is used as a singular noun, but for multiple actions (e.g. from the marketplace), action is used as the singular.

2022-05-03 08:21 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +* Continue working with the new changes and repeat!
Good point, thanks, I'm not quite sure where to fit it into the blog. I don't think it goes in this section about hosting on GitHub as much as in general guidance about using git, but I'll make sure I add this to my workshop materials on reproducible Matlab/version control for Matlab users.

2022-05-03 08:26 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +  * run MATLAB's [`checkcode` function](https://uk.mathworks.com/help/matlab/ref/checkcode.html) against the repo to look for problems in the code so you don't have to look for them manually?
The question marks.

2022-05-03 08:29 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +In brief, GitHub actions is a really, really, _really_ useful tool! Some examples of things I've done with them with MATLAB are: running tests when a pull request is made so that we can see that the
Yeah that's an arkward one, however in the following sentence you use "them" which is plural. So it's inconsistent to use singular in the previous sentence.

2022-05-03 08:40 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +In brief, GitHub actions is a really, really, _really_ useful tool! Some examples of things I've done with them with MATLAB are: running tests when a pull request is made so that we can see that the
hoisted by my own petard..

2022-05-03 08:51 UTC, davidwilby commented on _posts/2022-05-05-reproducible-matlab.md
> +MATLAB provides tools for [class-based testing](https://uk.mathworks.com/help/matlab/class-based-unit-tests.html); [testing applications](https://uk.mathworks.com/help/matlab/app-testing-framework.ht
Quite right, I've conflated two things.
In my defence, this is the way it was taught to me on a MathWorks course, it would appear that I've mis-absorbed the material.
Will correct. Thanks Rob.

2022-05-03 09:38 UTC, Robadob commented on _posts/2022-05-05-reproducible-matlab.md
> +#### Function-based testing
I still thing you should use the term 'unit testing' somewhere in this section. It's the general term which will stand out to people familiar with testing in other languages.

2022-05-04 11:01 UTC, Robadob approved these changes
Not given it as thorough a read through the second time, but looks good.

2022-05-05 08:19 UTC, merged