Promote rRSE job advert
RSE-Sheffield/RSE-Sheffield.github.io pull request #581
Opened 2022-05-12 15:20 UTC by bobturneruk

2022-05-12 16:11 UTC, davidwilby requested changes
Couple of typographic suggestions.


Do we need a call to action at the end? For instance "apply here" with another link to the advert.

Can we give an email address for questions as well?

2022-05-12 16:11 UTC, davidwyld commented on _posts/2022-05-12-rrse.md
> +6. **Reward and recognition** All of the Sheffield RSE team are employed within the academic careers pathway, a new flexible career development structure which recognises a broad range of research ou
```suggestion
6. **Reward and recognition.** All of the Sheffield RSE team are employed within the academic careers pathway, a new flexible career development structure which recognises a broad range of research outputs including software. The pathway provides a clear route for promotion up to the level of professor. 
```

Period at the end of bold text, for consistency.

2022-05-12 16:11 UTC, davidwyld commented on _posts/2022-05-12-rrse.md
> +3. **Make a difference.** Our team works with public /private sector organisations, and charities to give our output the best chance of making a positive difference outside the university. We also en
```suggestion
3. **Make a difference.** Our team works with public/private sector organisations, and charities to give our output the best chance of making a positive difference outside the university. We also enthuse about and participate in open research wherever possible.
```

2022-05-13 08:03 UTC, bobturneruk commented
Good spots and good points. Thanks!

2022-05-13 08:05 UTC, merged