RSE Blog post: xarray for earth
RSE-Sheffield/RSE-Sheffield.github.io pull request #59
Opened 2019-02-08 14:05 UTC by jmcook1186

Hi,

This pull request is for a post about xarray for the RSE blog, as discussed with Will F.
Please review and let me know any amends.

3 files committed: 
2019-02-08-xarray-for-earth.md to /posts
Sentinel_map.jpg to /assets/images/
Sentinel_map2.jpg to assets/images

2019-02-08 16:49 UTC, ptheywood requested changes
See the comments for minor changes.

2019-02-08 16:49 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +xarray works with two basic data structures – the DataArray and the DataSet
Missing `.`

2019-02-08 16:49 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +```
Syntax highlghting can be applied via:

    ```python

2019-02-08 16:49 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +```
Syntax highlghting can be applied via:

    ```python

2019-02-08 16:49 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +```
Syntax highlghting can be applied via:

    ```python

2019-02-08 16:49 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +![xarray's plot function output: top = classified surface, bottom = albedo map](/assets/images/Sentinel_map.jpg)
These images are currently rendering as incredibly large. I'll fix this with some CSS and a separate pull request so we can keep the markdown clean. (I.e. don't worry about this).

2019-02-08 16:49 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +# xarray for Earth Science
With how we render blog posts the (almost) replicated title seems unnecesary? 

![image](https://user-images.githubusercontent.com/628937/52492531-54a08800-2bc1-11e9-8e2d-c7328db31d0e.png)

2019-02-08 17:26 UTC, willfurnass commented on _posts/2019-02-08-xarray-for-earth.md
> +    S2vals[i,:,:] = S2BXvals # append to 'master' ND array
`S2vals` undefined at this point.

2019-02-08 17:27 UTC, willfurnass commented on _posts/2019-02-08-xarray-for-earth.md
> +vals = vals/10000 # correct unit from S2 L2A data to reflectance between 0-1
`vals /= 10000` more efficient

2019-02-08 17:36 UTC, ptheywood commented on _posts/2019-02-08-xarray-for-earth.md
> +![xarray's plot function output: top = classified surface, bottom = albedo map](/assets/images/Sentinel_map.jpg)
This is fixed as of #61

2019-02-08 17:45 UTC, jmcook1186 commented
Hi - thanks for the comments so far - all amended in the second commit

2019-02-11 12:08 UTC, ptheywood approved these changes

2019-02-11 16:53 UTC, merged

2019-02-11 16:53 UTC, willfurnass commented
Thanks for this @jmcook1186 !