Training update
RSE-Sheffield/RSE-Sheffield.github.io pull request #590
Opened 2022-06-17 13:46 UTC by bobturneruk

Resolves #589

2022-06-17 13:50 UTC, bobturneruk commented on _data/event-categories.yml
> +gitzerohero:
This let's us filter git courses out of events.

2022-06-17 14:25 UTC, ns-rse commented on _data/navigation.yml
>    subitems:
Why has the training statement been removed from the navigation?

2022-06-17 14:26 UTC, ns-rse commented on _data/event-categories.yml
> +gitzerohero:
Makes sense to move these out to their own category. :+1:

2022-06-17 14:29 UTC, ns-rse commented on pages/training/index.md
> +People working code for research, whether they are writing their first script to managing a complex software project need skills that academic training might not provide. The RSE Team's aspiration is
```suggestion
People working with code for research, whether they are writing their first script to managing a complex software project need skills that academic training might not provide. The RSE Team's aspiration is that all researchers who need these skills should be given the opportunity to learn them, either from the RSE Team, our University of Sheffield colleagues or other sources.
```

2022-06-17 14:31 UTC, ns-rse commented on pages/training/index.md
> +We can run courses where material is made openly available by others (e.g. The Carpentries).
Readers may not be aware of what The Carpentries are...

```suggestion
We can run courses where material is made openly available by others (e.g. [The Carpentries](https://carpentries.org)).
```

2022-06-17 14:35 UTC, ns-rse reviewed
All great improvements, some very minor points spotted.

2022-06-20 08:11 UTC, bobturneruk commented on _data/navigation.yml
>    subitems:
I wanted to make sure it was tied closely to the training courses stuff, and reduce the number of links people have to read.

2022-06-20 09:36 UTC, mondus requested changes
Looks good. A change relating to terminology around AI/ML suggested.

2022-06-20 09:36 UTC, mondus commented on _data/navigation.yml
> -    - title: Deep Learning
I wonder if this (and the link title page and intro) should perhaps be changed to "Artificial Intelligence and Machine Learning" to reflect the universities interests. Likewise the page could do with an update to provide some links back to the AI network and any other institutional resources.

2022-06-20 09:36 UTC, mondus commented on pages/training/deeplearning/index.md
> -In conjunction with [Nvidia Deep Learning Institue (DLI)](https://www.nvidia.com/dli), RSES offers various practical workshops on how to apply deep learning to your research. Details for these events
Could do with some general blurb and links to local resources and networks. I know this is a training page but it seems the most appropriate place to mention the AI network. 

If your making edits I also think he list of resources would be better above the previous events.

2022-06-20 10:02 UTC, bobturneruk commented on _data/navigation.yml
> -    - title: Deep Learning
I've changed the title.

2022-06-20 10:04 UTC, bobturneruk commented on pages/training/deeplearning/index.md
> -In conjunction with [Nvidia Deep Learning Institue (DLI)](https://www.nvidia.com/dli), RSES offers various practical workshops on how to apply deep learning to your research. Details for these events
Previous events should have gone prior to you seeing this. Hopefully just a rendering / caching thing.

2022-06-20 10:11 UTC, bobturneruk commented on pages/training/deeplearning/index.md
> -In conjunction with [Nvidia Deep Learning Institue (DLI)](https://www.nvidia.com/dli), RSES offers various practical workshops on how to apply deep learning to your research. Details for these events
I've put a mention in. Both the programming and AI/ML pages could do with separate reviews.

2022-06-20 10:33 UTC, bobturneruk commented on _data/navigation.yml
> -    - title: Deep Learning
Some links in. I've been pretty minimal here. Let me know if more is needed.

2022-06-20 10:34 UTC, bobturneruk commented
I've snuk in some pretty brittle looking jekyll to help people sign up to the mailing list if there are no current courses.

2022-06-21 15:33 UTC, mondus approved these changes

2022-06-21 15:33 UTC, mondus commented on _data/navigation.yml
> -    - title: Deep Learning
Looks good

2022-06-21 15:33 UTC, mondus commented on pages/training/deeplearning/index.md
> -In conjunction with [Nvidia Deep Learning Institue (DLI)](https://www.nvidia.com/dli), RSES offers various practical workshops on how to apply deep learning to your research. Details for these events
Can always expand upon this later.

2022-06-21 15:48 UTC, merged