Blog post: "Proving quality in research software"
RSE-Sheffield/RSE-Sheffield.github.io pull request #634
Opened 2022-10-11 15:42 UTC by davidwilby

I've reached a point with this blog where another pair of eyes or a few would be really helpful, I have to publish this on Thursday morning to coincide with international RSE day so any feedback would be really useful. It's only one step forward from a stream of consciousness at this stage so comments on structure or any missing explanation or clarity would be great too. Will also add an image or two before publishing also.

2022-10-12 15:03 UTC, bobturneruk approved these changes
Hopefully some helpful stuff in and amongst my musings here. I've got wrapped up in definitions. A really thought-provoking article!

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +title: "Proving quality in research software"
How about "Turbo-charge your career by demonstrating the quality of your research software"? Maybe not 😄 but perhaps "demonstrating" is better than "proving" (which I lazily read as **im**proving).

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +When it comes to 'traditional research outputs' (i.e. peer-reviewed publications), the dreaded journal impact factor has come to be the _de facto_ standard measure of the quality of a piece of resear
I didn't know markdown could do footnotes like that. Slick.

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +When it comes to 'traditional research outputs' (i.e. peer-reviewed publications), the dreaded journal impact factor has come to be the _de facto_ standard measure of the quality of a piece of resear
```suggestion
When it comes to 'traditional research outputs' (i.e. peer-reviewed publications), the dreaded journal impact factor has come to be the _de facto_ standard measure of the quality of a piece of research, however flawed we know it to be.[^dora] Along with numbers of citations[^citations], these measures are a big part of what's used to determine how worthy the author of some research is of: promotion, funding, recognition _etc_. But with software, we don't implicitly have the \*ahem\* *"luxury"* of impact factors and numbers of citations so using other ways of showing that our work has merit is something of a necessity, but how do we do that?
```

I'd also consider defining impact factor with a footnote.

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +As research software engineers (RSEs) or researchers who develop software & code, at some point we will need to provide evidence that our software actually has some effect on the world. Whether this
```suggestion
As research software engineers (RSEs) or researchers who develop software & code, at some point we will need to provide evidence that our software actually has some positive effect on the world. Whether this is for career progression, the REF,  just for your own peace of mind or any of a whole host of reasons, collecting usage data takes many forms but can often come as an afterthought.
```

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +I want to preface this blog by pointing out that simplifying a complex topic such as research quality down to a set of easily digestible metrics is a terrible idea. Publication itself demonstrates to
> Retraction rates actually inversely scale with impact factors (citation needed)

So a high impact factor ("good") means a low retraction rate (also "good")?

> most research in the 'top' journals is of excellent quality 

Do we know this? Is there any evidence e.g. from reproducibility projects? I think this statement may be too kind.

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +The concepts discussed in this article apply both to what I would term: research "quality" and research "impact", referring to the influence a research output has on academia and the world outside, r
I tend to think about "quality", "academic importance" and "impact". Which is a REF-y way of looking at it - separating academic impact from impact outside of academia. It may be worth mentioning that we routinely conflate importance and quality in academic circles i.e. if something is cited a lot, or happens to be in a high impact factor journal, it must be good. Whereas with impact, we often don't care about quality at all as long as it makes a lot of money or affects a lot of people.

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +For software, the evidence you use may have some similarities, but it's important to make the distinction between academia and the rest of the world. Some kinds of evidence are fairly straightforward
Sadly, I think you may need to explain REF and how academic progression stuff is derived from it. Otherwise, why would we have this big distinction between academic and non-academic "impact".

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +In an ideal world, assessors would have the time to assess your software on its own particular merits: code quality, extensibility, robustness and so on. But frankly, in all likelihood your software
JOSS?

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +> I was lead developer of software that enabled research on a GPP1.2M project, supporting 2 PhD Students and 2 PDRAs to publish 3 papers. The software also supports a community of researchers in the
These "quotes" are excellent. This is, though, more about impact / importance than quality. Quality measures might be 3rd party review or asserted via demonstrable good practise.

2022-10-12 15:03 UTC, bobturneruk commented on _posts/2022-10-13-evidence.md
> +title: "Proving quality in research software"
Quality and importance? Qualportance? Can software be of low quality and high importance? Anyone ever forced to use crap software? Or high quality and low importance? Beautifully engineered but for lost use case?

2022-10-12 15:05 UTC, ns-rse requested changes
Reads well, some very minor typos and thought there was one sentence that didn't flow well. Perhaps one area where I thought I'd like to know how the `Sire` and `BioSimSpace` projects had employed metric gathering but not essential and my be a bit too tangential to the post.

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +> I was lead developer of software that enabled research on a GPP1.2M project, supporting 2 PhD Students and 2 PDRAs to publish 3 papers. The software also supports a community of researchers in the
Minor typo...

```suggestion
> I was lead developer of software that enabled research on a GBP1.2M project, supporting 2 PhD Students and 2 PDRAs to publish 3 papers. The software also supports a community of researchers in the discipline and is publicly available as open source software with 20k downloads a week.
```

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +One way you can encourage citation of your software in publications, which will clearly show its value. If there's a paper associated with it, encourage its citation in your documentation and provide
Sentence feels a bit disjointed/incomplete in the middle, perhaps...

```suggestion
One way you can encourage citation of your software in publications, which will clearly show its value, is if there's a paper associated with it then in your documentation provide _pro forma_ citation text that can be used in publications. This lowers the barrier for others to cite your work.
```

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +* **Third party usage tracking** - Say your software is a web app, you could include a tool like [Google Analytics](https://analytics.google.com/) or [Plausible](https://plausible.io/) to gather and
Not really used them but unsure where you would "include" such tools, perhaps...
```suggestion
* **Third party usage tracking** - Say your software is a web app, you could employ a tool like [Google Analytics](https://analytics.google.com/) or [Plausible](https://plausible.io/) to gather and aggregate usage data.
```

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +* **Roll-your-own usage tracking** - If you'd rather keep your usage tracking under your own control, you could consider including a utility in your code for it to send data back to a web server at s
I'm pro-privacy and would advocate opt-in rather than opt-out to such data capture. That is more a personal view rather than a suggestion for change though.

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +Some examples of projects using this approach I was recently made aware of are [Sire](https://github.com/michellab/Sire) and [BioSimSpace](https://github.com/michellab/BioSimSpace), both open source
Could you say more on what each of these projects capture? Is it just when its been installed, how often its used or something else?

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +If your project is a package that's available via a public package repository like [PyPI](https://pypi.org/) or [CRAN](https://cran.r-project.org/) there are likely services available to provide stat
CRAN in particular has a high bar for inclusion of a package, making a PyPI package also

```suggestion
If your project is a package that's available via a public package repository like [PyPI](https://pypi.org/) or [CRAN](https://cran.r-project.org/) there are likely services available to provide stats for package downloads, for example [PyPI Stats](https://pypistats.org/) or [META CRAN](https://cranlogs.r-pkg.org/). In addition, it may be that merely making a package available via a major package repository is good evidence of quality in and of itself, since they typically enforce a certain standard and require proficiency to have published there.
```

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +Commercial software almost intrinsically has evidence metrics associated with it. If the software is the product itself you might already be collecting numbers of customers and fiscal measures that m
Very minor

```suggestion
Commercial software almost intrinsically has evidence metrics associated with it. If the software is the product itself you might already be collecting numbers of customers and fiscal measures that might be able to be used as evidence, or if the software is used inside a commercial organisation you have some involvement with (a spin-out for example) then numbers of sales, customers _etc_. might already be available for you to use.
```

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +The approach is much the same here too, but qualitative evidence may prove to be very important indeed. Ask the PI for a very, *very* strong testimonial and collect grant values, numbers of students,
Very minor

```suggestion
The approach is much the same here too, but qualitative evidence may prove to be very important indeed. Ask the PI for a very, *very* strong testimonial and collect grant values, numbers of students, publications _etc_. as well.
```

2022-10-12 15:05 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +On the other hand, consider early on in the project designing it in such a way that it can be used by a more general user base and/or be open source. This can require a bit more effort but in the gra
Not sure this paragraph is necessarily appropriate to **Very specific software** as worded it reads as though it might be better under the previous section of **Commercial software** as its advocating. Highly specific software is unlikely to generalisable too much, although would benefit from being open source (as most things do, never know who might be working on a similar area!).

2022-10-12 15:34 UTC, davidwyld commented on _posts/2022-10-13-evidence.md
> +I want to preface this blog by pointing out that simplifying a complex topic such as research quality down to a set of easily digestible metrics is a terrible idea. Publication itself demonstrates to
also needs citation, which I forgot

2022-10-12 15:35 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +title: "Proving quality in research software"
Also would like nicer with title-case.

2022-10-12 15:36 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +As research software engineers (RSEs) or researchers who develop software & code, at some point we will need to provide evidence that our software actually has some positive effect on the world. Whet
double space after `the REF,` (probably doesn't matter after MD has been processed.

2022-10-12 15:39 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +### Research Impact
You've used title-case for this heading, but the previous ones (and at a glance latter ones).
Consistency

2022-10-12 15:44 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +Whilst overly simplistic (and perhaps slightly misrepresentative in the case of frequency of downloads) a reader will get a much quicker and clearer idea of how great your software is from the latter
I was about to comment re downloads being a poor metric, yes.

2022-10-12 15:47 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +> I was lead developer of software that enabled research on a GBP1.2M project, supporting 2 PhD Students and 2 PDRAs to publish 3 papers. The software also supports a community of researchers in the
Did the software enable the research, or did the research fund/enable the software's development?

In the prior case, you're unlikely to know in many cases what 3rd party researchers are doing with your software (until they publish?).

2022-10-12 15:51 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +* **Last Resorts** - If your project is on GitHub, stars on the repository or number of clones are collected by default, but I wouldn't rely on this. Stars are a really unreliable measure of quality
No full stop end of the line?

2022-10-12 15:55 UTC, Robadob commented on _posts/2022-10-13-evidence.md
> +In an ideal world, assessors would have the time to assess your software on its own particular merits: code quality, extensibility, robustness and so on. But frankly, in all likelihood your software
Would probably be relevant to mention JOSS somewhere in this article, even if it's merely a passing mention rather than a detailed review.

2022-10-12 15:56 UTC, Robadob reviewed
Good idea, already got alot of good comments from bob & neil so I didn't add much.

2022-10-13 08:34 UTC, davidwilby commented on _posts/2022-10-13-evidence.md
> +Some examples of projects using this approach I was recently made aware of are [Sire](https://github.com/michellab/Sire) and [BioSimSpace](https://github.com/michellab/BioSimSpace), both open source
I won't put this link in the blog but if you're interested in the source https://github.com/michellab/Sire/blob/b2f3062789dcee37fe626a9d497e20a65066c267/src/sire/_thumbsup.py#L111

2022-10-13 09:01 UTC, ns-rse commented on _posts/2022-10-13-evidence.md
> +Some examples of projects using this approach I was recently made aware of are [Sire](https://github.com/michellab/Sire) and [BioSimSpace](https://github.com/michellab/BioSimSpace), both open source
Ta :+1:

2022-10-13 09:08 UTC, merged