November Newsletter
RSE-Sheffield/RSE-Sheffield.github.io pull request #648
Opened 2022-11-28 16:17 UTC by EdwinB12

2022-11-28 16:24 UTC, davidwilby requested changes
Nice one, there is A LOT in this newsletter! Couple of suggestions.

2022-11-28 16:24 UTC, davidwyld commented on _newsletters/2022-11-25-newsletter.md
> +#### News, Web and Publications
This heading is a bit repetitive of the one on line 17

2022-11-28 16:24 UTC, davidwilby commented on _newsletters/2022-11-25-newsletter.md
> +Research IT is providing a place for beginners or advanced users to expand their knowledge of HPC and different programming languages. The courses are part of the Doctoral Development Programme. For
I don't know that this list of sold out courses deserves a place above some scheduled courses with places available, maybe we should move it down.

2022-11-28 16:24 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [University of Sheffield Inaugural Annual Open Research Lecture](https://www.eventbrite.co.uk/e/university-of-sheffield-inaugural-annual-open-research-lecture-tickets-440984976937) - Lecture given
When?

2022-11-28 16:24 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [R course for Digital Humanities](https://n8cir.org.uk/events/r-digital-humanities/) - Following a similar format to the 2021 workshop, the course is a gentle introduction to R for text analysis. O
When?

2022-11-28 16:26 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +### Events
Would be nice to have a consistent date format

* Thursday 1 and Friday 2 December
* 2022-12-01 to 2022-12-03
* January 16, 2023
* 27–31 March 2023

etc

2022-11-28 16:27 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +### Events
Also they don;t appear to be in chronological order. Archer course is dec, but after something with a january deadline.

2022-11-28 16:28 UTC, davidwilby commented on _newsletters/2022-11-25-newsletter.md
> +### Events
> Would be nice to have a consistent date format

This should just be a running comment on newsletters at this point..

2022-11-28 16:28 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [28 November 2022 and 29 November 2022](https://rse.shef.ac.uk/training/workshop/2022-11-28-git-zero-hero)
Not worth advertising this course, it's already started.

2022-11-28 16:29 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [28 November 2022 and 29 November 2022](https://rse.shef.ac.uk/training/workshop/2022-11-28-git-zero-hero)
Wasn't there a meeting last week to discuss new dates? (Not sure who to bother about this for more info, I just recall it being mentioned)

2022-11-28 16:31 UTC, ns-rse commented on _newsletters/2022-11-25-newsletter.md
> +### Events
ISO8601!

2022-11-28 16:33 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [ARCHER2 Embedded CSE (eCSE) Support Call](https://www.archer2.ac.uk/ecse/calls/). The ARCHER2 eCSE call provides funding for up to 18 person months of an RSE/PDRA to work on codes to run on ARCHER
The deadline for this funding call has passed

2022-11-28 16:34 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [PhD at University of Bristol: Open spectroscopy in Environmental Sciences: Machine-learningaugmented analysis and interpretation ](https://www.bristol.ac.uk/media-library/sites/earthsciences/docum
Deadline?

2022-11-28 16:34 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [Wellcome PhD studentships](https://pheds-dtc.ac.uk/). Training the next generation of researchers in high-quality research of complex multi-component public health interventions and policies.
deadline?

2022-11-28 16:34 UTC, EdwinB12 commented on _newsletters/2022-11-25-newsletter.md
> +#### News, Web and Publications
How do we feel about 'Web and Publications' instead? Is that still too repetitive?

2022-11-28 16:34 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [Mathematical and computational foundations of artificial intelligence](https://www.ukri.org/opportunity/mathematical-and-computational-foundations-of-artificial-intelligence/). Apply for funding t
Deadline?

2022-11-28 16:35 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +#### Funding
Similar to events, consistent date format and chronological ordering would be nice, makes it alot easier to scan.

2022-11-28 16:35 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [Oracle for Research Project Awards](https://www.oracle.com/research/project-awards/) Oracle Research (this years sponsors of the RSE conference) have an open grants program to sponsor research pro
When?

2022-11-28 16:36 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [Wellcome PhD studentships](https://pheds-dtc.ac.uk/). Training the next generation of researchers in high-quality research of complex multi-component public health interventions and policies.
Possibly a bit more context here too, expect phd studentships aren't of interest to most the readership (but what do I know someone submit it to the slack channel).

2022-11-28 16:46 UTC, davidwilby commented on _newsletters/2022-11-25-newsletter.md
> +#### News, Web and Publications
Follow your heart.

2022-11-28 16:55 UTC, EdwinB12 commented on _newsletters/2022-11-25-newsletter.md
> +* [28 November 2022 and 29 November 2022](https://rse.shef.ac.uk/training/workshop/2022-11-28-git-zero-hero)
We've decided some dates internally but not yet made the events. We decided it best not to advertise these yet until the eventbrite event has been created

2022-11-28 16:56 UTC, EdwinB12 commented on _newsletters/2022-11-25-newsletter.md
> +### Events
Yup this is fair point, generally just copied from whatever format someone put in the Slack. Lazy Edwin! Anyway, I'll convert to ISO8601 and order chronologically

2022-11-28 17:01 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [28 November 2022 and 29 November 2022](https://rse.shef.ac.uk/training/workshop/2022-11-28-git-zero-hero)
Could atleast hint that ones for months x/y/z will be announced soon, so keep an eye out on the mailing list.

2022-11-28 17:22 UTC, EdwinB12 commented on _newsletters/2022-11-25-newsletter.md
> +* [Oracle for Research Project Awards](https://www.oracle.com/research/project-awards/) Oracle Research (this years sponsors of the RSE conference) have an open grants program to sponsor research pro
Doesn't appear to be a deadline as far as I can tell. Worth putting something like 'Deadline N/A' or 'Open Call' or just leave blank?

2022-11-28 17:23 UTC, EdwinB12 commented on _newsletters/2022-11-25-newsletter.md
> +* [ARCHER2 Embedded CSE (eCSE) Support Call](https://www.archer2.ac.uk/ecse/calls/). The ARCHER2 eCSE call provides funding for up to 18 person months of an RSE/PDRA to work on codes to run on ARCHER
Good spot, thanks

2022-11-28 17:44 UTC, EdwinB12 commented on _newsletters/2022-11-25-newsletter.md
> +Research IT is providing a place for beginners or advanced users to expand their knowledge of HPC and different programming languages. The courses are part of the Doctoral Development Programme. For
Yer thats fair, I'll move our two courses to the bottom of the training section

2022-11-28 17:47 UTC, Robadob commented on _newsletters/2022-11-25-newsletter.md
> +* [Oracle for Research Project Awards](https://www.oracle.com/research/project-awards/) Oracle Research (this years sponsors of the RSE conference) have an open grants program to sponsor research pro
Yeah one of those will suffice

2022-11-29 09:01 UTC, EdwinB12 commented
Thanks for the reviews @Robadob @davidwilby , believe I've addressed the changes: 

1. Changed all dates to 2022-11-29 format 
2. Ensure all events have location and date as first bit of information
3. Moved events and funding to chronological order
4. Removed events and funding opportunities that have passed
5. Removed Git training date and added a note to look out for newly advertised course dates
6. Moved git and deep learning training to the bottom of the training section

2022-11-29 09:05 UTC, Robadob approved these changes
Looks good to me.

There's still a couple of dates in the Web and Pubs section, but probably fine in that context.

2022-11-29 09:54 UTC, EdwinB12 commented
Thanks @Robadob , I'll wait for Davids review before merging. Happy with a merge commit or do you want it squashing?

2022-11-29 10:00 UTC, davidwilby approved these changes

2022-11-29 10:22 UTC, Robadob commented
> Thanks @Robadob , I'll wait for Davids review before merging. Happy with a merge commit or do you want it squashing?

Personally I'm a big fan of squashing then rebase + merge. As I like a linear history without junk split commits. But this isn't my repo, so not my problem.

2022-11-29 13:24 UTC, merged