Posts for 2023 Git courses
RSE-Sheffield/RSE-Sheffield.github.io pull request #655
Opened 2022-12-20 09:04 UTC by ns-rse

Two events pages and a blog post on the Git courses scheduled for next year.

2022-12-20 09:23 UTC, davidwilby requested changes
:+1: Nice work getting all this together!
Couple of minor corrections.

Also, would it be a good idea to add to the training posts something like:
> Please note this workshop will be held **in person** - if you would like to attend an online course instead, please see...

and *vice versa*?

2022-12-20 09:23 UTC, davidwilby commented on 2022-12-20-upcoming-git-zero-to-hero.md
> +---
This file should be in `_posts/`.

2022-12-20 09:23 UTC, davidwilby commented on _events/workshop-2023-01-26-git-zero-hero.md
> +permalink: /training/workshop/2022-11-28-git-zero-hero
```suggestion
permalink: /training/workshop/2023-01-26-git-zero-hero
```

2022-12-20 09:23 UTC, davidwilby commented on _events/workshop-2023-03-06-git-zero-hero.md
> +permalink: /training/workshop/2022-11-28-git-zero-hero
```suggestion
permalink: /training/workshop/2023-03-06-git-zero-hero
```

2022-12-20 12:42 UTC, ns-rse commented on 2022-12-20-upcoming-git-zero-to-hero.md
> +---
That is what I get for working before my brain is awake, sorry and thanks.

2022-12-20 13:19 UTC, davidwilby approved these changes
I hope you don't mind me taking the liberty of moving the blog post to the `_posts/` folder (for blog md files), sorry if this is incorrect.

2022-12-20 13:20 UTC, davidwilby commented on 2022-12-20-upcoming-git-zero-to-hero.md
> +---
Don't apologise please, that's why we have reviews!

2022-12-20 13:21 UTC, ns-rse commented
Not at all, I thought I did that...

```
❱ history | grep "git mv" | grep 2022-12-20
15619  2022-12-20 12:42  git mv 2022-12-20-upcoming-git-zero-to-hero.md _events/.
```

Not sure why it didn't come through when I staged and pushed. :shrug:

2022-12-20 13:28 UTC, merged

2022-12-20 13:58 UTC, davidwilby commented
> Not at all, I thought I did that...
> 
> ```
> ❱ history | grep "git mv" | grep 2022-12-20
> 15619  2022-12-20 12:42  git mv 2022-12-20-upcoming-git-zero-to-hero.md _events/.
> ```
> 
> Not sure why it didn't come through when I staged and pushed. shrug

You moved it to `_events/` rather than `_posts/` assuming that this is a blog post and not an event.

2022-12-22 10:07 UTC, ns-rse commented
Gah, I'm an idiot! :facepalm: