add november 2023 draft newsletter
RSE-Sheffield/RSE-Sheffield.github.io pull request #716
Opened 2023-11-02 11:28 UTC by MILeach

2023-11-02 11:39 UTC, davidwilby requested changes
Looking good! Thanks @MILeach - one or two suggestions.

2023-11-02 11:39 UTC, davidwilby commented on _newsletters/2023-11-02-newsletter.md
> +The next meeting is scheduled for 2pm on Wednesday 9th August.
```suggestion
The next meeting is scheduled for 2pm on Wednesday 8th November.
```

2023-11-02 11:39 UTC, davidwilby commented on _newsletters/2023-11-02-newsletter.md
> +### Training
I would take out the whole training section here, there aren't any events organised by the RSE team scheduled and the CRS site is now defunct.

2023-11-02 15:42 UTC, ns-rse commented on _newsletters/2023-11-02-newsletter.md
> +
Moving this from above to where it should be sorry.

Its all wrapped up and hidden under MyDevelopment which I don't find particularly easy to navigate. There is no useful hierarchical structure and I only found them by searching for nothing but filtering Vendor for "IT Services".

Each course has at least one event scheduled, some up to 5. Some that are due to run soon have 65 places available, others are fully booked.

No idea where these have been advertised :shrug: , I don't recall seeing it on the RSE mailing list.


## R

* [R for Statistics and Data Visualisation](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/943cfaf5-cb85-4b58-9af7-16064ae8752b) 2023-11-09 (fully booked, 5 people on waiting list)

## Python

* [Python for Data Science I](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/653bbdfb-ab61-451b-894f-c38de64f7dbc) 2023-21-05 (fully booked, 5 people on waiting list)
* [Python Programming 1](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/d2c02e5b-4b2e-43dd-9860-07ccca5c0400) 2023-11-27 (39 places available) 2023-12-11 (fully booked, 2 people on waiting list).
* [Python Programming 2](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/8ebd2c6f-2c1b-499f-9866-9c78ae625172) 2023-12-01 (65 places available) 2023-12-12 (3 places available).
* [Python Programming 3](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/d54e003f-6948-4e89-b245-57e4a1b5b587) 2023-12-04 (65 places available) 2024-01-16 (2 places available).
* [Supervised Machine Learning 1](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/184a44dc-acdd-4908-8246-3d9897492f06) 2023-11-17 (14 places available) 2023-11-30 (91 spaces available) 2023-12-14 (7 spaces available) 2024-01-12 (13 spaces available) 2024-02-02 (13 spaces available)
* [Supervised Machine Learning 2](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/87c9ec1e-648a-4d60-8a99-0a7eccf53577) 2024-01-15 (fully booked, 2 people on waiting list) 2024-01-29 (10 spaces available)
*  [Temporal Analysis in Python](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/31ad16b9-5d28-48cf-8a46-1437e2248c8c) 2023-11-24 (4 places available) 2024-01-19 (6 spaces available)

Its quite bizzare that the advanced courses have more sessions scheduled than the intro ones, perhaps some have already run :thinking: 

## Matlab

* [Introduction to Matlab 1](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/d96972b1-cb9e-475e-b680-a83d3fa57972) 2023-11-09 (1 place available)
* [Introduction to Matlab 2](https://mydevelopment.csod.com/ui/lms-learning-details/app/event/0746d395-7a7d-45b9-9cee-3f7220e28202) 2023-11-30 (9 places available)

2023-11-02 15:43 UTC, ns-rse commented on _newsletters/2023-11-02-newsletter.md
> +#### Volunteer Positions
Pedantic Markdown linting (see pending #700 ) would want a space between paragraph and new lines (would also wrap lines at 120 characters).

2023-11-02 22:05 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- Free Software Foundation Europe (FSFE) published a [short explainer video on free software](https://media.fsfe.org/w/p/9gYSyoEYggsqBExLWjRejL).
is this in the right section?

2023-11-02 22:06 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- The Alan Turing Institute is hosting the UK’s national showcase of data science and artificial intelligence (AI), [AI UK 2024](https://ai-uk.turing.ac.uk/). Tickets are now available.
19-24 march

2023-11-02 22:06 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- The N8 CIR are hosting a [half-day event](https://n8cir.org.uk/events/data-access-for-digital-health/) on the 8th November to discuss the challenges of data access in the field of digital health an
2023!
Be useful to make this list chronological.

2023-11-02 22:08 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- The [UK RSECon](https://society-rse.org/rse-conference-2024/) and [US RSECon](https://docs.google.com/forms/d/e/1FAIpQLSfxkbo-6eF2NENsrWwb44_Bb32UNCzgP2d6-z3Hq8HxbYCWYA/viewform) are each looking f
Worth highlighting the deadline, I think RSECON UK deadline is Tuesday next week. So VERY close.

2023-11-02 22:09 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- The Carpentries, who promote inclusive teaching of data and coding skills, are [looking for candidates for their board of directors](https://carpentries.org/blog/2023/09/board-of-directors-election
Deadline was late October, this is defunct.

2023-11-02 22:09 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- The Journal of Open Source Software (JOSS) has issued a [call for editors](https://blog.joss.theoj.org/2023/10/call-for-editors).
Deadline 6th Nov, very close!

2023-11-02 22:10 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> +- The Open Bioinformatics Foundation have opened a call for applications for the [OBF Event Fellowship](https://www.open-bio.org/2023/10/19/event-fellowship-2023-3/) which aims to increase diversity
Deadline 1st Dec

2023-11-02 22:10 UTC, Robadob commented on _newsletters/2023-11-02-newsletter.md
> ++ [Making research software more visible and reusable: Open Source Software and
6th Dec 12:00-13:00

2023-11-02 22:11 UTC, Robadob requested changes
See my individual comments, mostly about highlighting deadlines.

2023-11-06 15:32 UTC, Robadob approved these changes
Looks good.

Little unsure about the "full, n people on waiting list" level of detail, but eh.

2023-11-06 15:54 UTC, merged