2024-03 Newsletter
RSE-Sheffield/RSE-Sheffield.github.io pull request #753
Opened 2024-03-14 10:34 UTC by twinkarma

2024-03-14 11:54 UTC, ns-rse requested changes
Thanks for putting this together @twinkarma .

I noticed the date in the header needs tweaking and some of the footer sections which is copied from previous is kind of duplication but not a big deal.

2024-03-14 11:54 UTC, ns-rse commented on _newsletters/2024-03-14-newsletter.md
> +date: 2024-01-14T17:00:00Z+0100
```suggestion
date: 2024-03-14T17:00:00Z+0100
```

2024-03-14 11:54 UTC, ns-rse commented on _newsletters/2024-03-14-newsletter.md
> +[RSE support via the Centre for Machine Intelligence](https://rse.shef.ac.uk/collaboration/cmi-rse/) is available to
This and the next paragraph where it talks about Code Clinics might be considered duplication of content already covered above.

2024-03-14 12:15 UTC, tdjames1 commented on _newsletters/2024-03-14-newsletter.md
> +We're in the process of finalising some forthcoming RSE training events so keep an eye on our
There are several Git/GitKraken sessions lined up, could add dates here?

2024-03-14 12:26 UTC, ns-rse commented on _newsletters/2024-03-14-newsletter.md
> +We're in the process of finalising some forthcoming RSE training events so keep an eye on our
These have now been published to the RSE site and appear under the Events page linked.

I wrote them and made a PR a couple of weeks ago but forgot to merge, only realised when Joe said there was nothing listed. I started writing new pages before I remembered that the PR was waiting to be merged :facepalm: 

No harm in listing them here though to highlight they are scheduled.

2024-03-14 16:42 UTC, twinkarma commented on _newsletters/2024-03-14-newsletter.md
> +[RSE support via the Centre for Machine Intelligence](https://rse.shef.ac.uk/collaboration/cmi-rse/) is available to
Thanks, I'll remove it.

2024-03-14 16:43 UTC, twinkarma commented on _newsletters/2024-03-14-newsletter.md
> +We're in the process of finalising some forthcoming RSE training events so keep an eye on our
Cheers @tdjames1 I'll list the next few git session here

2024-03-15 11:40 UTC, ns-rse approved these changes
Cool, good work @twinkarma and thanks for adding the Git courses and other training details.

2024-03-15 12:31 UTC, twinkarma commented
Thanks for your reviews @ns-rse and @tdjames1 !

2024-03-15 12:31 UTC, merged