Add FAQ to gh enterprise page
RSE-Sheffield/RSE-Sheffield.github.io pull request #761
Opened 2024-05-03 15:59 UTC by twinkarma

2024-05-03 19:57 UTC, ns-rse commented on pages/training/gh-enterprise.md
> +delegates) of the Github Organisation in which it belongs to. Additional owners of the repository can an external
```suggestion
delegates) of the Github Organisation in which it belongs to. Additional owners of the repository can be external
```

2024-05-03 19:57 UTC, ns-rse commented on pages/training/gh-enterprise.md
> +collaborator to UoS.
```suggestion
collaborators to UoS.
```

2024-05-03 19:59 UTC, ns-rse requested changes
Minor grammar suggestions, otherwise good to merge.

2024-05-13 17:01 UTC, twinkarma commented
Thanks @ns-rse !

2024-05-14 08:14 UTC, ns-rse approved these changes
Good to go :+1:

2024-05-14 09:57 UTC, merged