2024 rse call
RSE-Sheffield/RSE-Sheffield.github.io pull request #766
Opened 2024-05-13 13:24 UTC by Romain-Thomas-Shef

This is the publication of the RSE call for free project time. Please have a look at it (I am far from being an expert in webdev so please do not hesitate to correct it I am wrong).

2024-05-13 21:33 UTC, ubdbra001 commented on pages/collaboration/RSEtime_call2024/call2024.md
> +For this first call, the team will select two projects.**Selected proposals will receive 6 months @ 45-50% FTE of RSE support**. The start date will be decided by the RSE team based on the project ti
Final sentence needs another look

2024-05-13 21:34 UTC, ubdbra001 commented on pages/collaboration/RSEtime_call2024/call2024.md
> +An application template for this call has been prepared and is available [here](https://docs.google.com/document/d/1yzqS8gS-iCQ4HgM3dBcYEfYsS9E1Zm28CguZrTMl22M/edit?usp=sharing). We kindly request ap
missing 'a' on 'application'

2024-05-14 08:17 UTC, ns-rse commented on pages/collaboration/RSEtime_call2024/call2024.md
> +For this first call, the team will select two projects.**Selected proposals will receive 6 months @ 45-50% FTE of RSE support**. The start date will be decided by the RSE team based on the project ti
```suggestion
For this first call, the team will select two projects.**Selected proposals will receive 6 months @ 45-50% FTE of RSE support**. The start date will be decided by the RSE team based on the project timeline and RSEs availability. The duration of the project will not exceed 6 months but might be shortened with a higher FTE fraction (e.g. 3 months @ 100%). In addition, the collaboration will be continuous and can not be split into multiple shorter, disjointed periods of time.
```

2024-05-14 08:24 UTC, ns-rse requested changes
Good spot by @ubdbra001 on the paragraph, I've made a suggestion for that.

I noticed the Bullet points need tweaking to render with a space between the unordered list marker and the text that follows..

2024-05-14 08:24 UTC, ns-rse commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Rational [max 600 words]:** Provide a brief description of the research project, its objectives and the role of software or computation methods in achieving these objectives.
Need spaces after the bullet points for them to be correctly recognised as an unordered list in Markdown (obviously the other points below also need spaces!).

```suggestion
- **Rational [max 600 words]:** Provide a brief description of the research project, its objectives and the role of software or computation methods in achieving these objectives.
```

2024-05-14 08:24 UTC, ns-rse commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Fit:** Request fits the objective of the call.
Spacing, plus other bullet points.

```suggestion
- **Fit:** Request fits the objective of the call.
```

2024-05-14 08:24 UTC, ns-rse commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-Deadline for proposal submission: June 28th
Ditto

```suggestion
- Deadline for proposal submission: June 28th
```

2024-05-14 08:24 UTC, ns-rse commented on pages/collaboration/RSEtime_call2024/call2024.md
> +For inquiries or assistance with the proposal submission process, please contact Neil Shephard (<a href="mailto:n.shephard@sheffield.ac.uk">n.shephard@sheffield.ac.uk</a>, Chair of the selection Pane
Doesn't need changing but might save a few keystrokes in the future. I've found you can use Markdown for `mailto:` links too.

```suggestion
For inquiries or assistance with the proposal submission process, please contact Neil Shephard ([n.shephard@sheffield.ac.uk](mailto:n.shephard@sheffield.ac.uk), Chair of the selection Panel) and/or Romain Thomas, ([romain.thomas@sheffield.ac.uk](mailto:romain.thomas@sheffield.ac.uk), Head of the RSE group).
```

2024-05-14 09:08 UTC, Romain-Thomas-Shef commented on pages/collaboration/RSEtime_call2024/call2024.md
> +For this first call, the team will select two projects.**Selected proposals will receive 6 months @ 45-50% FTE of RSE support**. The start date will be decided by the RSE team based on the project ti
I accepted Neil's suggestions for this.

2024-05-14 09:11 UTC, Romain-Thomas-Shef commented on pages/collaboration/RSEtime_call2024/call2024.md
> +An application template for this call has been prepared and is available [here](https://docs.google.com/document/d/1yzqS8gS-iCQ4HgM3dBcYEfYsS9E1Zm28CguZrTMl22M/edit?usp=sharing). We kindly request ap
fixed

2024-05-14 10:31 UTC, ns-rse approved these changes
I took the liberty of adding spaces between all unordered list items (`-`) and the first word of each sentence so they all render.

Looks ready to merge :+1:

2024-05-15 10:28 UTC, Robadob requested changes

2024-05-15 10:28 UTC, Robadob commented on _layouts/home.html
> +                <p><a class="sm-a" href="/collaboration/RSEtime_call2024/">Apply for 6 months free at the point of use RSE time. Deadline 28th of June 2024.</a></p>
6 months @50% FTE, would be clearer to state as 3 months here. If 'FTE is not specified people would probably assume 100%

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +To support the University research community we are pleased to announce a **call for proposals which will be supported by free at point-of-use RSE collaboration**. This initiative aims to facilitate
> **call for proposals which will be supported by free at point-of-use RSE collaboration**.

This bit reads a bit weird. I don't think we should call an effective internal grant 'free at point of use' it's not a widely available free service. 

Maybe just name it '2024 RSE collaboration grant's call for proposals.' After which you can go on to explain it.

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Rational [max 600 words]:** Provide a brief description of the research project, its objectives and the role of software or computation methods in achieving these objectives.
```suggestion
-**Abstract [max 600 words]:** Provide a brief description of the research project, its objectives and the role of software or computation methods in achieving these objectives.
```

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Rational [max 600 words]:** Provide a brief description of the research project, its objectives and the role of software or computation methods in achieving these objectives.
Maybe also clarify the description should be accessible to reviewers outside their field.

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +The panel reviewing the projects will consist of members from the Research Software Engineering team and Data Analytics Service [DAS]. The panel will gather on July where a final selection will be do
```suggestion
The panel reviewing the projects will consist of members from the Research Software Engineering team and Data Analytics Service [DAS]. The panel will gather in July where a final selection will be done.
```

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Practicality:** How easy will it be for the RSE to get into the project?
```suggestion
-**Practicality:** How easy will it be for the RSE to join the project?
```

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Project risks [max 200 words]:** What could make the collaboration go wrong? Describe briefly what are the potential risks of this project. (An obvious example: lack of data or no access to sensit
```suggestion
-**Project risks [max 200 words]:** What issues may cause the collaboration to be unsuccessful? Briefly describe the potential risks to the project. (A common example: lack of data or no access to sensitive data)
```
Lots I didn't like about this one.

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Impact statement [max 200 words]:** Explain how access to free RSE time would benefit the project and contribute to its success or broader research goals.
Should this also mention the universities 3 priorities, not that I recall. Might be the one university vision, but I'd need to check.

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +#### Eligibility
Are you not going to explicitly say ML projects were covered by the prev CMI call, so are not eligible for this grant.

2024-05-15 10:28 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +The University of Sheffield recognizes the critical role that Research Software Engineers (RSEs) play in advancing scientific research. The University of Sheffield Research Software Engineering (RSE)
> The team has since grown to 11 members and has worked on a variety of projects with all faculties at the University.

Possibly worth extending this to highlight that we've worked on small internally funded projects, large international consortiums (EU) and industrial. To highlight a different dimension of our breadth.

2024-05-15 10:29 UTC, Robadob commented
Sorry about the delayed review, I wrote all these comments 2 days ago, but appears they weren't visible as I was doing it in review mode rather than comment and hadn't selected a decision.

2024-05-15 11:19 UTC, Romain-Thomas-Shef commented on pages/collaboration/RSEtime_call2024/call2024.md
> +#### Eligibility
I believe we should not restrict make constraints like this. If we have projects that are more suitable to the CMI-RSE call we could tell them no for this call but that we can take that on other scheme, under the CMI umbrella.

2024-05-15 11:33 UTC, Romain-Thomas-Shef commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Impact statement [max 200 words]:** Explain how access to free RSE time would benefit the project and contribute to its success or broader research goals.
I have added in the introduction: 'To support the *One University* vision and the University research community'. I am not sure how we could include this in the impact statement (if that's where you thought it could go).

2024-05-15 11:33 UTC, Romain-Thomas-Shef commented
@Robadob I believe I have answered all your comments.

2024-05-15 11:33 UTC, Robadob approved these changes

2024-05-15 11:34 UTC, Robadob commented on pages/collaboration/RSEtime_call2024/call2024.md
> +-**Impact statement [max 200 words]:** Explain how access to free RSE time would benefit the project and contribute to its success or broader research goals.
Yeah, it's an awkward one but something senior uni people are probably keen to be pushed by anything they're effectively funding.

2024-05-17 07:46 UTC, merged