FAQ for upgrading R (response to CVE-2024-27322)
RSE-Sheffield/RSE-Sheffield.github.io pull request #769
Opened 2024-06-05 09:08 UTC by willfurnass

Our response re https://hiddenlayer.com/research/r-bitrary-code-execution/.  Keen to get pushed out soon.

2024-06-05 10:57 UTC, ns-rse requested changes
Very detailed upgrade guide, made a few suggestions and some questions.

I wonder if we need to bother touching on whether people use `renv` and the need to upgrade those, but on the flip side it might be taking the level of detail too far. I'd kind of expect people using `renv` to be able to handle that themselves.

2024-06-05 10:57 UTC, ns-rse commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +    * Use packages from a reputable source with a history of well maintained packages.
Whilst this is true and good advice my understanding of the issue is that it is serialised R objects `.Rds` / `.Rdx` perhaps worth emphasising that...

```suggestion
    * Use packages from a reputable source with a history of well maintained packages. 
    * Use only serialised (`.Rds` / `.Rdx`) objects from trusted sources, be very wary of such files shared openly on the internet.
```

2024-06-05 10:57 UTC, ns-rse commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +Upgrading to R version 4.4.0 is mandatory as it addresses recent security vulnerabilities. It's important to remember that even with the latest version there is still a risk with untrusted RDS files.
Perhaps pedantic but "mandatory" is a strong word with specific connotations/implications if what is being advised (upgrading) isn't undertaken. How is failure to comply going to be assessed, if at all, and dealt with?

2024-06-05 10:57 UTC, ns-rse commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +We recommend that you read the documentation for your chosen text editor. If you cannot find an appropriate method, then we recommend starting the update process by deleting your older version of you
R installation is _always_ completely independent of RStudio (even if it can be managed from within) and its probably not the text editor that people need to look at. VSCode won't allow you to do this, nor will Emacs. Its more likely their systems package manager (Debian/Ubuntu would be `apt`; Arch Linux `pacman`; Gentoo `portage`; OSX `homebrew`) that people need to look at and we can't double guess what that would be for everyone. Perhaps pointing people to the generic install instructions on CRAN would be most appropriate.

```suggestion
We recommend that you read the documentation for the package manager of your operating system. If you cannot find an appropriate method, then we recommend reading the FAQ linked from the [The Comprehensive R Archive Network](https://cloud.r-project.org/).
```

2024-06-05 10:57 UTC, ns-rse commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +The upgrade to R 4.4.0 will happen automatically and you will not need to take any further action to update R itself. You will need to recreate your R package library for R 4.4.0 - reinstalling any R
Should instructions on upgrading packages be included?

I would typically run...

```
update.packages()
```

...in the new R version after installation, but I have hooks setup under Arch to rebuild packages after an update of R.

2024-07-10 11:38 UTC, willfurnass commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +Upgrading to R version 4.4.0 is mandatory as it addresses recent security vulnerabilities. It's important to remember that even with the latest version there is still a risk with untrusted RDS files.
Given how/where R is used we can't enforce this but strong wording is required to motivate people here given the number/diversity of unmanaged R installations across the researcher community.

2024-07-10 11:45 UTC, willfurnass commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +The upgrade to R 4.4.0 will happen automatically and you will not need to take any further action to update R itself. You will need to recreate your R package library for R 4.4.0 - reinstalling any R
How safe is `update.packages()`?  Any typical footguns?

2024-07-10 11:47 UTC, willfurnass commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +We recommend that you read the documentation for your chosen text editor. If you cannot find an appropriate method, then we recommend starting the update process by deleting your older version of you
Thanks; I haven't made the exact specified change but have added wording of that nature.  Think those FAQs are pretty imposing and keen not to push people towards them too readily.

2024-07-10 11:47 UTC, willfurnass commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +    * Use packages from a reputable source with a history of well maintained packages.
Good suggestion; ta

2024-07-10 11:48 UTC, willfurnass commented
> I'd kind of expect people using renv to be able to handle that themselves.

Agree.

2024-07-10 11:51 UTC, ns-rse commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +The upgrade to R 4.4.0 will happen automatically and you will not need to take any further action to update R itself. You will need to recreate your R package library for R 4.4.0 - reinstalling any R
Occasionally I've encountered the odd package that will fail to compile (under Linux).

I know for Debian based systems there are builds for ["_many packages on CRAN and Bioconductor_"](https://cran.r-project.org/bin/linux/debian/) but can't speak to those nor the situation under OSX (I suspect they are built from source too, I do have a Macbook but haven't had recourse to use R on it much).

2024-07-19 13:14 UTC, willfurnass commented on _posts/2024-06-05-faqs-for-upgrading-r.md
> +The upgrade to R 4.4.0 will happen automatically and you will not need to take any further action to update R itself. You will need to recreate your R package library for R 4.4.0 - reinstalling any R
Added brief mention of `update.packages()`

2024-07-19 13:21 UTC, merged