Cmi call on hold
RSE-Sheffield/RSE-Sheffield.github.io pull request #783
Opened 2024-06-27 14:34 UTC by Romain-Thomas-Shef

I am closing momentarily the CMI RSE call (too many projects). We will re-open it later this year.

2024-06-27 16:20 UTC, ptheywood commented on pages/collaboration/cmi-rse/cmi-rse.md
> +<span style="color:red"> Due to the amount of preject with received, this call is on hold until November 2024.</span>.
```suggestion
<span style="color:red"> Due to the amount of projects received, this call is on hold until November 2024.</span>.
```
```suggestion
<span style="color:red"> Due to the amount of preject with received, this call is on hold until November 2024.</span>.
```

2024-06-27 16:26 UTC, ptheywood requested changes
Made a suggestion to fix a typo + removed a word, otherwise fine. 

I've also not tired it, but as the website is bootstrap based we could use a `bd-callout` for emphasis. I.e. 

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/628937/d09d79a8-335a-4b40-9e00-399b333181c2)
![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/628937/d09d79a8-335a-4b40-9e00-399b333181c2)

```
<div class="bd-callout bd-callout-danger">
<strong>This is a danger callout.</strong> Example text to show it in action.
</div>
```

2024-06-27 16:34 UTC, ptheywood commented on pages/collaboration/cmi-rse/cmi-rse.md
> +<span style="color:red"> Due to the amount of preject with received, this call is on hold until November 2024.</span>.
Could also use a bootstrap 4 `alert` for visual emphasis.

```suggestion
<div class="alert alert-danger" role="alert">Due to the amount of projects received, this call is on hold until November 2024.</div>
```

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/628937/09fa6e12-d687-464a-b5b1-4d932a96ad0f)

instead of 

![image](https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/assets/628937/b5f4b6cd-965d-4fc5-a64c-c68770b68010)

Though either is fine.

2024-06-28 10:51 UTC, ptheywood approved these changes

2024-06-28 11:01 UTC, merged

2024-06-28 11:01 UTC, Romain-Thomas-Shef commented
Thanks @ptheywood !