Update alumni information
RSE-Sheffield/RSE-Sheffield.github.io pull request #787
Opened 2024-07-02 15:15 UTC by ubdbra001

Adjusted to show where the alumni moved onto immediately after leaving the RSE team, and when they left. Closes #439.

I think I've got most of the info correct, but it'd be useful if someone who has been around for a bit longer than me could double check.

Thanks!

2024-07-02 16:03 UTC, ptheywood requested changes
Mostly looks correct to me, just a question about John's immediate role following the end of his secondment into the team. 

I'm not sure on the actual answer, so have tagged John in the comment.

2024-07-02 16:03 UTC, ptheywood commented on _people/john-charlton.md
> +John left the RSE Sheffield team in 2020 to take up a role as a Postdoctoral Research Fellow at the University of Sheffield, in Neopath, part of the School of Clinical Dentitry
Looks like John only started in Neopath/dentistry in Nov 2023. 

https://coolmule0.github.io/about/#neopath

I'm not sure on the best way to describe John's secondment in the team ending, be it to complete his PhD or do other RA work in the uni immediately after.

@coolmule0 - any suggestions / preference?

2024-07-02 16:08 UTC, ns-rse approved these changes
For those I know anything about (Anna, David Wilby, Will, Bob, Fariba, Paul) all looks accurate and reworking of others looks fine, left a comment as to whether Phil Tooley's email address `@sheffield.ac.uk` is still valid. Brief search only returns hits to our own pages!

2024-07-02 16:08 UTC, ns-rse commented on _people/phil-tooley.md
>  * Email: phil.tooley (at) sheffield.ac.uk
Should we remove this if its not a valid email address?

2024-07-02 19:16 UTC, ubdbra001 commented on _people/phil-tooley.md
>  * Email: phil.tooley (at) sheffield.ac.uk
Probably a good shout, same with Bob's email?

2024-07-02 19:18 UTC, ns-rse commented on _people/phil-tooley.md
>  * Email: phil.tooley (at) sheffield.ac.uk
:facepalm: Yes, Bob's too then, I did scan through to see if there were others but obviously missed that so good :eye: 's

2024-07-11 11:16 UTC, coolmule0 commented on _people/john-charlton.md
> +John left the RSE Sheffield team in 2020 to take up a role as a Postdoctoral Research Fellow at the University of Sheffield, in Neopath, part of the School of Clinical Dentitry
These suggest changes sound the easiest to read, even if not strictly true  :+1:

2024-07-30 10:46 UTC, ubdbra001 commented on _people/john-charlton.md
> +John left the RSE Sheffield team in 2020 to take up a role as a Postdoctoral Research Fellow at the University of Sheffield, in Neopath, part of the School of Clinical Dentitry
Thanks @coolmule0 
Happy with this @ptheywood ?

2024-08-12 10:34 UTC, ptheywood approved these changes

2024-08-12 10:40 UTC, Robadob approved these changes

2024-08-12 10:40 UTC, Robadob commented on _people/paul-richmond.md
> +Paul was a co-founder of the RSE team and led its growth and development from three staff to a team of roughly 12 full time employees over a period of six years. He left the RSE Sheffield team in 202
"three" and "12" in the same sentence, consistency pls, albeit not your fault.

2024-08-12 10:40 UTC, merged