September 2024 newsletter; LunchBytes October 2024-10-22
RSE-Sheffield/RSE-Sheffield.github.io pull request #814
Opened 2024-09-11 13:13 UTC by ns-rse

2024-09-11 13:18 UTC, Robadob commented on _events/lunchbytes-2024-10-22.md
> +We'll use sli.do for questions, link will be circulated during the event.
maybe turn sli.do into a link, for those unfamilar with it.

2024-09-11 13:18 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +title: Month Year Newsletter
title needs updating

2024-09-11 13:19 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +## The University of Sheffield Research Software Engineering Community Newsletter March 2024
Month needs updating

2024-09-11 13:19 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +## The University of Sheffield Research Software Engineering Community Newsletter March 2024
```suggestion
## The University of Sheffield Research Software Engineering Community Newsletter September 2024
```

2024-09-11 13:19 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +title: Month Year Newsletter
```suggestion
title: September 2024 Newsletter
```

2024-09-11 13:19 UTC, Robadob commented on _events/lunchbytes-2024-10-22.md
> +We'll use sli.do for questions, link will be circulated during the event.
```suggestion
We'll use [sli.do](sli.do) for questions, link will be circulated during the event.
```

2024-09-11 13:21 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +- [Data Technical Lead at University of Sheffield](https://www.jobs.ac.uk/job/DJM932/data-technical-lead)
```suggestion
- [Data Technical Lead at University of Sheffield](https://www.jobs.ac.uk/job/DJM932/data-technical-lead) (Closes 26th Sept)
```

2024-09-11 13:21 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +  Sheffield](https://www.jobs.ac.uk/job/DJL697/research-software-engineer-in-ai-and-machine-learning)
```suggestion
  Sheffield](https://www.jobs.ac.uk/job/DJL697/research-software-engineer-in-ai-and-machine-learning) (Closes 25th Sept)
```

2024-09-11 13:22 UTC, Robadob commented on _newsletters/2024-09-12-newsletter.md
> +[LunchBytes](https://rse.shef.ac.uk/community/lunch-bytes/) are short talks from the research community on research
Shouldn't this mention Romain's new scheduled one?

2024-09-11 13:22 UTC, Robadob approved these changes
See comments first, all small stuff

2024-09-11 13:24 UTC, ubdbra001 commented on _newsletters/2024-09-12-newsletter.md
> +Clinic](https://docs.google.com/forms/d/e/1FAIpQLScGXS55qjU0D0Zcz-KHOVcNTahcr3YC3H0OpoKBo3lWXWED5A/viewform)? We're keen
It may be worth linking to the code clinic page on the RSE site that gives a bit more detail (and also links to the form) rather than just the form:
https://rse.shef.ac.uk/support/code-clinic/

2024-09-11 13:27 UTC, ns-rse commented on _newsletters/2024-09-12-newsletter.md
> +[LunchBytes](https://rse.shef.ac.uk/community/lunch-bytes/) are short talks from the research community on research
It's mentioned above under the **Training** header and as that event will run in October I thought I'd leave it at that for now and the October newsletter can highlight it under this section.

2024-09-12 10:01 UTC, tdjames1 commented on _events/lunchbytes-2024-10-22.md
> +date: 2024-10-21
```suggestion
date: 2024-10-22
```

2024-09-12 10:01 UTC, tdjames1 commented on _events/lunchbytes-2024-10-22.md
> +As code and software become an ever bigger part of research (its likely that [around 1/3 of researchers write
```suggestion
As code and software become an ever bigger part of research (it's likely that [around 1/3 of researchers write
```

2024-09-12 10:03 UTC, tdjames1 requested changes
Couple of fixes for the LunchBytes event.

2024-09-12 12:51 UTC, merged