blog: Summary of funded proposals 2024
RSE-Sheffield/RSE-Sheffield.github.io pull request #819
Opened 2024-09-23 09:58 UTC by ns-rse

Short summary on the call for proposals and research projects that were funded.

@Robadob : I know you've already started work on HYBRID but wanted to keep the text simple.

2024-09-23 10:20 UTC, Robadob requested changes
I've not given it a full read through yet, but you switch between HYBRID and HYBIRD, it should be the latter.

2024-09-23 10:25 UTC, Robadob commented on _posts/2024-09-24-funded-proposals.md
> +Geo-Technical Engineering group and is written using C++. It combines the Discrete Element Method (DEM) and the Lattice
```suggestion
[HYBIRD][hybrid] is software developed by [Dr Alessandro Leonardi][alessandro] and his research group with the
Geo-Technical Engineering group and is written using C++. It combines the Discrete Element Method (DEM) and the Lattice
```

> his research group with the Geo-Technical Engineering group 

This also reads weird

You may want to check how he would like this phrased. As I understand, it began as his PhD thesis ~10 years ago, and has since grown and is now used widely in the domain.

2024-09-23 10:25 UTC, Robadob commented on _posts/2024-09-24-funded-proposals.md
> +allowed the investigation of the formation of granular fronts in free-surface flows, enhancing understanding of
```suggestion
Boltzmann Method (LBM) to simulate complex particle-fluid interactions. These fluid-structure interactions have
allowed the investigation of the formation of granular fronts in free-surface flows, enhancing understanding of
```

2024-09-23 10:32 UTC, ns-rse commented on _posts/2024-09-24-funded-proposals.md
> +Geo-Technical Engineering group and is written using C++. It combines the Discrete Element Method (DEM) and the Lattice
Ta removed suggestions.

I was going to get everything in shape from our end then contact PIs and ask them if they were happy with the text. I should have mentioned this intention in the PR in the first place.

2024-09-23 11:09 UTC, Robadob commented on _posts/2024-09-24-funded-proposals.md
> +Work will be undertaken by [Robert Chisholm][rob] to re-write the build system in [CMake][cmake] which will make it
```suggestion
Work will be undertaken by [Dr Robert Chisholm][rob] to re-write the build system in [CMake][cmake] which will make it
```

If title's are being used for PIs, probably worth using mine.

More broadly, this could be significantly shorter.

> Work will be undertaken by [Dr Robert Chisholm][rob] to modernise HYBIRD's build system, address the limiting factors of it's performance and enable it to take advantage of GPU parallelisation. The broad objectives of this project are to reduce barriers to entry for new users and to increase the performance to enable faster and larger research experiments .

(I also want to less subtly tie the above quote to improving impact, but can't find appropriate phrasing).

could go even further and "Dr Robert Chisholm, a performance optimisation and GPU parallelisation specialist from our team," 🤣 This is supposed to be lowkey marketing of our team after all, so plug the teams attributes as much as possible.

Feels like a good thing to dump relevant info into chatgpt and ask it to draft you some promotional fluff.

2024-09-25 10:52 UTC, Robadob approved these changes
Looks ok, though still unsure with the wording of Alexandro and his multiple groups.

2024-09-25 15:05 UTC, ns-rse commented
Thanks @Robadob as you will have seen I've contacted PIs for feedback and suggestions and will incorporate their changes before publishing.

2024-09-26 08:06 UTC, merged