October 2024 Newsletter
RSE-Sheffield/RSE-Sheffield.github.io pull request #825
Opened 2024-10-09 15:49 UTC by Robadob

2024-10-09 18:36 UTC, ns-rse requested changes
Thanks for knocking this up so quickly @Robadob especially with how busy you've been the last few weeks :+1: 

Bunch of minor things, many pedantic and can be safely ignored. Some more important such as a couple of dates seemed to be out.

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +    - Weds Oct 23rd 12-1pm - Beyond open access: Democratising knowledge through accessible research outputs. [Book your place here](https://www.eventbrite.co.uk/e/beyond-open-access-democratising-kn
Nice way of avoiding duplication between Open Access Week and Open Research Conversations :+1:

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +- [2024] [A Vision on Open Science for the Evolution of Software Engineering Research and Practice](https://arxiv.org/abs/2405.12132)
I think its useful to mark pre-prints as such as they've not been peer-reviewed...

```suggestion
- [2024] **Pre-print** [A Vision on Open Science for the Evolution of Software Engineering Research and Practice](https://arxiv.org/abs/2405.12132)
```

Could easily go at the end of the line though, no particular style or preference here.

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +- [pyOpenSci Fall Festival 2024](https://www.eventbrite.com/e/pyopensci-fall-festival-2024-registration-1000762657047) (Oct 29th - Nov 1st) - A week of events to empower scientists to write better co
@ptheywood has dropped this in late today, date will have passed come the next newsletter...

```suggestion
- [pyOpenSci Fall Festival 2024](https://www.eventbrite.com/e/pyopensci-fall-festival-2024-registration-1000762657047) (Oct 29th - Nov 1st) - A week of events to empower scientists to write better code and share their outcomes openly.
- [DiRAC GPU Hackathon, Durham University](https://dirac.ac.uk/training_events/dirac-nvidia-hackathon-2024/) (Nov 26-28th), application deadline 12pm October 16th. 
```

Adding here so its in chronological order.

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +- [pyOpenSci Fall Festival 2024](https://www.eventbrite.com/e/pyopensci-fall-festival-2024-registration-1000762657047) (Oct 29th - Nov 1st) - A week of events to empower scientists to write better co
Other events have dates before link but realistically doesn't make much difference...

```suggestion
- Oct 29th to Nov 1st - [pyOpenSci Fall Festival 2024](https://www.eventbrite.com/e/pyopensci-fall-festival-2024-registration-1000762657047) - A week of events to empower scientists to write better code and share their outcomes openly.
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +- [UK Technology Specialists Network Conference](https://itss.org.uk/uk-technology-specialists-network-conference-2025/) April 29-30th 2025
As above following dates first...

```suggestion
- April 29-30th 2025 - [UK Technology Specialists Network Conference](https://itss.org.uk/uk-technology-specialists-network-conference-2025/) 
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +- [2024] [Research Software Engineering: Bridging Knowledge Gaps](https://drops.dagstuhl.de/entities/document/10.4230/DagRep.14.4.42)
As with the pre-print making it clear its not peer-reviewed pulication.

```suggestion
- [2024] **Seminar Report** [Research Software Engineering: Bridging Knowledge Gaps](https://drops.dagstuhl.de/entities/document/10.4230/DagRep.14.4.42)
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +will be given in a [LunchBytes session 2024-10-22](../events/lunchbytes-2024-10-22.html). The full syllabus is now live on [MyDevelopment](https://mydevelopment.csod.com/ui/lms-learning-details/app/c
`<pedantic>`Hard wrap to match rest of paragraph`</pedantic>`

```suggestion
will be given in a [LunchBytes session 2024-10-22](../events/lunchbytes-2024-10-22.html). The full syllabus is now live on 
[MyDevelopment](https://mydevelopment.csod.com/ui/lms-learning-details/app/curriculum/06573f55-12e4-44f1-be4c-fac5ea9d6851) (requires login).
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +Introduction to the Command-Line for Bioinformatics - November 27th 13:00 - 16:00 (£32 for students and £80 for staff)
```suggestion
- Introduction to the Command-Line for Bioinformatics - November 27th 13:00 - 16:00 (£32 for students and £80 for staff)
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +    - Mon 10th 10am - [Safe Researcher Training](https://ukdataservice.ac.uk/events/safe-researcher-training-67/)
Link says its 14th Oct

```suggestion
    - Mon Oct 14th 10am - [Safe Researcher Training](https://ukdataservice.ac.uk/events/safe-researcher-training-67/)
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +#### Jobs
`<pedantic>`Linting would suggest spacing`</pedantic>`

```suggestion

#### Jobs
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +There are two positions within the University of Sheffield currently being advertised.
```suggestion
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +-
```suggestion
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +The next meeting is scheduled for 2pm on Wednesday 18th September 2024.
```suggestion
The next meeting is scheduled for 2pm on Wednesday 6th November 2024.
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +[lunchbytes-organisers-group@sheffield.ac.uk](mailto:lunchbytes-organisers-group@sheffield.ac.uk) or suggest topics
Was mentioned today that Farhad will be taking over organising these, we should make sure that he's on this mailing list.

I've tried joining [https://groups.google.com/a/sheffield.ac.uk/g/lunchbytes-organisers-group](https://groups.google.com/a/sheffield.ac.uk/g/lunchbytes-organisers-group) but without success, page isn't found.

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +The Sheffield Bioinformatics Core is pleased to announce a schedule of courses for the new academic year. These courses provide an introduction to the R programming language, Unix environment (requir
Pedantic line wrapping...

```suggestion
The Sheffield Bioinformatics Core is pleased to announce a schedule of courses for the new academic year. These courses 
provide an introduction to the R programming language, UNIX environment (required for the use of the University's High
 Performance Computing facilities) and also specific applications in RNA-sequencing.
```

2024-10-09 18:36 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +You can now sign-up for these courses using myDevelopment (search for "bioinformatics"). Course charges still apply, and upon sign-up we will contact you for a valid grant code or cost centre. In-per
Pedantic line wrapping...

```suggestion
You can now sign-up for these courses using myDevelopment (search for "bioinformatics"). Course charges still apply, and 
upon sign-up we will contact you for a valid grant code or cost centre. In-person attendance is encouraged, but 
online options are also available.
```

2024-10-09 18:45 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +    - Weds Oct 23rd 12-1pm - Beyond open access: Democratising knowledge through accessible research outputs. [Book your place here](https://www.eventbrite.co.uk/e/beyond-open-access-democratising-kn
I just put the next event from each, did notice the overlap.

2024-10-09 18:47 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +The next meeting is scheduled for 2pm on Wednesday 18th September 2024.
whoops

2024-10-09 18:49 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +[lunchbytes-organisers-group@sheffield.ac.uk](mailto:lunchbytes-organisers-group@sheffield.ac.uk) or suggest topics
Yeah, I wasn't sure how to phrase that given nothing yet in the pipeline.

Not sure about the missing group, maybe wilby owned it so it got deleted?

2024-10-09 18:50 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +The Sheffield Bioinformatics Core is pleased to announce a schedule of courses for the new academic year. These courses provide an introduction to the R programming language, Unix environment (requir
my text editor supports word-wrap, waste of screen space if it's force wrapped different to my editor window..

2024-10-09 18:51 UTC, Robadob commented
Need to review date formatting when I have more attention span left, otherwise think things are addressed.

2024-10-10 08:44 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +will be given in a [LunchBytes session 2024-10-22](../events/lunchbytes-2024-10-22.html). The full syllabus is now live on [MyDevelopment](https://mydevelopment.csod.com/ui/lms-learning-details/app/c
![image](https://github.com/user-attachments/assets/79170afc-51f6-40bb-bdcf-4ac9c842c349)
It looks fine in my text editor without any changes 🤷‍♂️

2024-10-10 08:57 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +will be given in a [LunchBytes session 2024-10-22](../events/lunchbytes-2024-10-22.html). The full syllabus is now live on [MyDevelopment](https://mydevelopment.csod.com/ui/lms-learning-details/app/c
My pedantry with line wraps is less to do with how it appears in editors which will do soft line-wraps, and in Emacs you get an indicator that these are soft-wraps with little arrows at the side...

![soft-wrapped-lines](https://github.com/user-attachments/assets/2b1ad4b6-d2de-46e3-8302-b1576f9fa64f)

...rather when it comes to line diffing and finding errors/rendering differences its much harder to see these in really long chunks of text. That is somewhat ameliorated with the `--word-diff=color` but I've just got a old habit of hard-wrapping lines (well not so much a habit, it just happens automatically in my editor or its done by linters).

As I say, its pedantic and doesn't matter as it doesn't affect the rendered content which is wrapped automatically based on the available space.

2024-10-10 08:58 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +There are two positions within the University of Sheffield currently being advertised.
Not currently positions being advertised and there was the announcement of a moratorium on recruitment.

2024-10-10 09:01 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +There are two positions within the University of Sheffield currently being advertised.
I think you're reviewing an old version this should be gone.

2024-10-10 09:04 UTC, Robadob commented on _newsletters/2024-10-10-newsletter.md
> +will be given in a [LunchBytes session 2024-10-22](../events/lunchbytes-2024-10-22.html). The full syllabus is now live on [MyDevelopment](https://mydevelopment.csod.com/ui/lms-learning-details/app/c
Good diff checkers typically highlight affected characters within a line if tokens have changed but most of the line remains the same.

e.g.
![image](https://github.com/user-attachments/assets/f185b762-9143-4c52-a89e-2816e123a699)

or

![image](https://github.com/user-attachments/assets/c9cdf528-627e-4131-b8c1-9744e88b6c9b)

2024-10-10 09:13 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +- Until Nov 10th - [MATLAB Shorts Mini Hack](https://uk.mathworks.com/matlabcentral/contests/2024-matlab-mini-hack.html): Use upto 2,000 characters ofr MATLAB code to generated a MATLAB movie and win
```suggestion
- Until Nov 10th - [MATLAB Shorts Mini Hack](https://uk.mathworks.com/matlabcentral/contests/2024-matlab-mini-hack.html): Use upto 2,000 characters of MATLAB code to generated a MATLAB movie and win prizes.
```

2024-10-10 09:40 UTC, ns-rse commented on _newsletters/2024-10-10-newsletter.md
> +There are two positions within the University of Sheffield currently being advertised.
Indeed, apologies, I thought GitHub kept things fresh but it seems not.

2024-10-10 14:41 UTC, merged