Rework projects page
RSE-Sheffield/RSE-Sheffield.github.io pull request #840
Opened 2024-11-19 16:05 UTC by ubdbra001

2025-01-15 12:21 UTC, ubdbra001 commented
Does it work when there is no image included for project?

2025-01-20 15:06 UTC, EdwinB12 commented
@ubdbra001 - Any preference on where the images should be located? assets/images?

2025-01-20 16:36 UTC, EdwinB12 commented
Ignore this!

2025-01-20 17:26 UTC, EdwinB12 commented
@ubdbra001 - Any idea what the ideal picture shape size is? We should put that in the template as a comment

2025-04-14 09:57 UTC, ns-rse commented
Hi @ubdbra001 

I'm looking to solicit a testimonial from the PI of the HYBRID project that @Robadob worked on recently and see there is now such a field which includes the `author` and `quote`. I realise most of this work is on the technical side but was wondering if you had in mind any particular questions/content/angles that should be included when asking for feedback?

Thanks in advance,

@ns-rse

2025-04-14 10:11 UTC, ubdbra001 commented
> @ubdbra001 - Any idea what the ideal picture shape size is? We should put that in the template as a comment

I've set max-height to be 250px and the width will be dynamic, on my screen the containing box is ~350px. So, images with ~4:3 ratio would fit well in there.

2025-04-14 10:19 UTC, ubdbra001 commented
> Hi @ubdbra001
> 
> I'm looking to solicit a testimonial from the PI of the HYBRID project that @Robadob worked on recently and see there is now such a field which includes the `author` and `quote`. I realise most of this work is on the technical side but was wondering if you had in mind any particular questions/content/angles that should be included when asking for feedback?
> 
> Thanks in advance,
> 
> @ns-rse

For me the aim of this page is to highlight what the RSE team contributes to research, so I suppose: In the view of the PI/author what specific impact did the RSE have on that project and what does it mean for that research project/area?
e.g. Did they facilitate a type of research that couldn't have been done otherwise? Did they accelerate research in an existing project/area? Did they allow more complex and/or robust results from a project?

2025-05-27 12:45 UTC, ns-rse commented
Hi @ubdbra001 

I received the following testimonial from Alessandro Leonardi about his HYBRID project which @Robadob worked on...

> Collaborating with the Research Software Engineering (RSE) team has been a highly constructive experience that has made a tangible difference on how my research group works. I am a civil engineering researcher, and I often rely on numerical methods, but the challenges we face with our in-house software, particularly around performance and usability, require a level of software engineering expertise that goes well beyond what is typically available within our research group.
The RSE team brought in-depth technical knowledge that helped us identify and address several key bottlenecks in the code. In particular, they supported the development of a GPU-enabled version of our fluid solver and contributed to improving the memory management routines. These changes led to a noticeable reduction in simulation times and improved the stability of our models. I was lucky to work with a Software Engineer who is an expert in this type of implementation, which made the process very smooth.
> Beyond the technical improvements, the collaboration helped raise the standard of software development within our group. Working with the RSE team encouraged us to adopt more systematic development practices, improve our documentation, and consider long-term maintainability. This has directly benefited our PhD students and research staff, who now engage with the codebase more confidently and productively.

I'll keep an eye on when this template is merged and then use it to add the above (sticking it here in part so I don't forget about it).

2025-07-01 08:31 UTC, Robadob commented on assets/images/project_images/life_on_mars.png
If this is to be merged, presumably be want to remove the stock images?

2025-07-16 08:12 UTC, ns-rse requested changes
Some fields need updating in the Electricity Demand page but I I expect you already know these @ubdbra001 

I wondered if using the DOI for publications would be preferable than URLs which can change.

One minor grammatical error spotted too.

2025-07-16 08:12 UTC, ns-rse commented on _case_studies/ElectricityDemand.md
> +testimonial:
Dummy testimonial fields need updating.

2025-07-16 08:12 UTC, ns-rse commented on _case_studies/ElectricityDemand.md
> +software_link:
Links here also need updating.

2025-07-16 08:12 UTC, ns-rse commented on _case_studies/ElectricityDemand.md
> +publication_links:
Ditto for publications if there are any.

2025-07-16 08:12 UTC, ns-rse commented on _case_studies/example_project_template.md
> +publication_links:        # Links to published material associated with project. Not required.
Would it be worth having `doi:` as a field here? They're meant to be more permanent that `url:`.

2025-07-16 08:12 UTC, ns-rse commented on pages/collaboration/projects/projects.md
> +The Research Software Engineering team at Sheffield has worked on projects involving a variety of methods and technologies, below are some of the projects we have either worked on are are currently w
```suggestion
The Research Software Engineering team at Sheffield has worked on projects involving a variety of methods and technologies, below are some of the projects we have either worked on or are currently working on:
```

2025-10-08 15:13 UTC, ubdbra001 commented on pages/collaboration/projects/projects.md
> +The Research Software Engineering team at Sheffield has worked on projects involving a variety of methods and technologies, below are some of the projects we have either worked on are are currently w
Good spot!

2025-10-08 15:16 UTC, ubdbra001 commented on _case_studies/example_project_template.md
> +publication_links:        # Links to published material associated with project. Not required.
I agree DOIs are probably better.
I want to keep URL, but don't want to handle the logic of having both. So, I've added a note to say that DOI's are preferred in the URL field

2025-10-08 15:18 UTC, ubdbra001 commented
I suspect `ElectrictyDemand.md` will be replaced/deleted as part of this PR, so I'm not too bothered about keeping it up to date.

2025-10-15 16:21 UTC, ns-rse approved these changes

2025-11-19 12:30 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +        <img src="/assets/images/project_images/{{ project.image }}">
IMO it would be nicer if this could be a hot link, by forcing the `/assets/images/project_images` to be included in the yaml frontmatter instead for local images. 

This would allow re-use of images already in the website repository too (i.e. if in a blog post) without duplication.

2025-11-19 12:33 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      RSE(s): <em> {{ project.rses | join: ", " }} </em>
The `(s)` here can be made dynamic, by only including if the length of the array of RSEs is more than 1.


```suggestion
      RSE{% if project.rses.size > 1 %}(s){% endif %}: <em> {{ project.rses | join: ", " }} </em>
```

2025-11-19 12:37 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +        <img src="/assets/images/project_images/{{ project.image }}">
Alternatively if the image path does not start with `https://` or `/` then including the expected path could be an option to support both?

2025-11-19 12:45 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      <b>Software: </b><a href = "{{ project.software_link['url']}}">{{ project.software_link['name'] }}</a>
Multiple links for the software might be nice, i.e. github + zenodo + pypi + docs.

I.e. not putting forcing them to be in publication(s).

2025-11-19 12:50 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      <b>Publication(s):</b>
(s) could be made dynamic.
```suggestion
      <b>Publication{% if project.publication_links.size > 1 %}(s){% endif %}:</b>
```

2025-11-19 12:51 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      <b>Publication(s):</b>
The publication(s) header is included even if ther eare no elements in `project.publication_links`.

the block should probably be wrapped in `{% if project.publication_links.size > 0 %}` 

See the `Trustworthy Machine Learning Approaches to Electricity Demand Modelling` project as an example without any publications.

2025-11-19 13:00 UTC, ptheywood commented on _case_studies/example_project_template.md
> +end_date:                 # End date of project in DD-MM-YYYY format
Probably something to make a separate issue to handle (nicer) in the future, but for repeat-offenders like FLAMEGPU how should we define the start and end date(s) when there's gaps in funded time? 

Best option with the current set up is probably:

- Use the first start date
- Use the last end date
- Use the `funding_sources` with date periods in the `name`? (I.e.  `EPSRC <code> form XXXX-YY-ZZ to AAAA-BB-CC` or similar?

2025-11-19 13:30 UTC, Robadob commented on _case_studies/example_project_template.md
> +end_date:                 # End date of project in DD-MM-YYYY format
can end date be left blank and treated as "until present"

2025-11-19 13:31 UTC, Robadob commented on _case_studies/example_project_template.md
> +end_date:                 # End date of project in DD-MM-YYYY format
I would argue FLAMEGPU is not a project. Primage was, striuvad was, fujitsu was.

FLAMEGPU mostly steals time, besides commercialisation etc.

2025-11-19 15:26 UTC, Robadob commented
@ubdbra001 

If we are listing project start/end (e.g. duration) we should probably include FTE otherwise people may assume every project listed is 100% or some other value when that's very much not the case. Seems like important context.

2025-11-20 10:11 UTC, jmafoster1 commented
@ubdbra001 @EdwinB12, should we decide on a consistent format for multiple PIs? In this PR, @ubdbra001 has gone with an array, which displays as "name1, name2", where in #954, @EdwinB12 has gone with just the string "name1 and name2". I guess arrays are programatically better, but I quite like the "and". I have no strong preference, but the inconsistency between the two is a little jarring.

UPDATE: Not sure how easy it would be to implement, but I think my preferred solution would be to have the field be an array and then have the logic be
```
if len(pi_name) == 1:
  return pi_name
return ", ".join(pi_name[:-1]) + " and " + pi_name[-1]
```
This would give us
[name1] -> name1
[name1, name2] -> name1 and name2
[name1, name2, name2] -> name1, name2 and name3

2025-11-20 16:39 UTC, EdwinB12 commented
@jmafoster1 - I think this is a good idea. Lets say multiple authors should be added as arrays and then that logic can be added later

2025-11-20 17:03 UTC, ubdbra001 commented on pages/collaboration/projects/projects.md
> +        <img src="/assets/images/project_images/{{ project.image }}">
Agreed.
Will look into updating it as you suggest.

2025-11-20 17:06 UTC, ubdbra001 commented on pages/collaboration/projects/projects.md
> +      <b>Software: </b><a href = "{{ project.software_link['url']}}">{{ project.software_link['name'] }}</a>
Fair point, will add it as an issue to address later (so we can merge the current PRs without rebasing/merging).

2025-11-20 17:12 UTC, ubdbra001 commented
@jmafoster1 I also agree, I'll take a look to see if your suggestion is quick to implement, and will include it in this PR if so.

2025-11-20 19:49 UTC, ubdbra001 commented
Added, though I forgot how much of a pain the Liquid templating language is compared to Jijna...

2025-11-21 11:24 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      border-left:8px solid var(--uos-deep-violet-70);
This might conflict (well just not exist, not an actual conflict) with the colour pallette changes in #935 (Think I got rid of the `-70` shades).

Difficult to fix now anyway, just need to be aware depending on merge-order (I'll fix it later, just need to remember / do a full css pass of the website at some point).

2025-11-21 11:26 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      Collaborator(s): <em>{{ project.collaborators | join: ", " }}</em>
```suggestion
      Collaborator{% if project.collaborators.size > 1 %}(s){% endif %}: <em>{{ project.collaborators | join: ", " }}</em>
```

`collaborator` feels a bit wrong to me? (not sure why) but matches the other use of (s).

2025-11-21 11:30 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      {%- if project.rses.size > 2 %}
We can add a liquid templating include to approximate a function that would do this. 

I.e. create `list-of-names.html` or something, with this logic but taking an input (i.e. mapping `project.rses` / `project.collaboartors` to the same variable. 

Then just do `{% include list-of-names.html list=project.rses %}` or somethign to that effect. I'll give it a go.

2025-11-21 12:10 UTC, ptheywood commented on pages/collaboration/projects/projects.md
> +      {%- if project.rses.size > 2 %}
See #956

2025-11-21 16:38 UTC, martinjohndyer commented on pages/collaboration/projects/projects.md
> +      RSE{% if project.rses.size > 1 %}(s){% endif %}: <em>{% include join_list_commas_and.html list=project.rses %}</em>
I know this came from @ptheywood's suggestion, but wouldn't it make sense to remove the brackets around the s if there are more than one? Right now we have `RSE: Joe Blogs` and `RSE(s): Joe Blogs and John Smith`, but `RSEs`: in the latter case would be neater. Also applies to Publication(s) etc.
```suggestion
      RSE{% if project.rses.size > 1 %}s{% endif %}: <em>{% include join_list_commas_and.html list=project.rses %}</em>
```

2025-11-21 16:38 UTC, martinjohndyer commented on pages/collaboration/projects/projects.md
> +      Collaborator(s): <em>{% include join_list_commas_and.html list=project.collaborators %}</em>
```suggestion
      Collaborator{% if project.collaborators.size > 1 %}s{% endif %}: <em>{% include join_list_commas_and.html list=project.collaborators %}</em>
```
Another (s). Although I'm not 100% on this one, e.g. Edwin's `Collaborator: Advanced Infrastructure Technology Ltd` seems slightly off to me to be using the singular for a company? If I was writing it I'd probably say something like "In collaboration with:", but I might be overthinking it.

2025-11-21 16:38 UTC, martinjohndyer commented on pages/collaboration/projects/projects.md
> +      <b>Publication{% if project.publication_links.size > 1 %}(s){% endif %}:</b>
```suggestion
      <b>Publication{% if project.publication_links.size > 1 %}s{% endif %}:</b>
```

Remove the brackets around the (s) again.

2025-11-21 16:38 UTC, martinjohndyer commented on pages/collaboration/projects/projects.md
> +      <b>Funding source(s): </b>
```suggestion
      <b>Funding source{% if project.funding_sources.size > 1 %}s{% endif %}: </b> 
```
And another one.

2025-11-21 16:38 UTC, martinjohndyer commented on pages/collaboration/projects/projects.md
> +        <img src="/assets/images/project_images/{{ project.image }}">
Being able to add an image caption (e.g. for attribution) and/or alt-text (for accessibility) would be nice.

2025-11-21 16:38 UTC, martinjohndyer commented on pages/collaboration/projects/projects.md
> +
Before the `software_link`, it would be nice to have an (optional) `project_link` field, for cases where the project is big enough to have its own site. For example GOTO has the overall project website (https://goto-observatory.org), likewise GridLive could have https://sites.google.com/sheffield.ac.uk/gridlive/ as the project link and https://api.gridlive.shef.ac.uk/docs as the software link, rather than putting the former under "Publications".

2025-11-21 16:40 UTC, ubdbra001 commented on _case_studies/example_project_template.md
> +end_date:                 # End date of project in DD-MM-YYYY format
I agree with Rob about Flame, but I do think it's worth considering including info about funding periods on the page. I've added it to my stretch goals list.

2025-11-21 16:49 UTC, ubdbra001 commented on pages/collaboration/projects/projects.md
> +      Collaborator(s): <em>{% include join_list_commas_and.html list=project.collaborators %}</em>
Pete highlighted that 'collaborator' singular does feel a bit odd and I agree (a bit Vichy France maybe?)
I think "in collaboration with" or "in partnership with" may be better, but I'll see if I can find something more concise.

2025-12-03 15:02 UTC, merged